# Generated by Django 5.2.15 on 2026-06-11 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('search', 'Search'), ('company_dossier_open', 'Company dossier open'), ('review_submit_start', 'Review submit start'), ('review_submit_complete', 'Review submit complete'), ('claim_profile_click', 'Claim profile click'), ('claim_profile_submit', 'Claim profile submit'), ('audit_lead_submit', 'Audit lead submit'), ('guide_cta_click', 'Guide CTA click')], db_index=True, max_length=48)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='companies.company')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='analytics_a_event_t_6c35be_idx')],
            },
        ),
    ]
