# Generated by Django 5.2.15 on 2026-06-11 17:15

import apps.seo.indexability
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_status', models.CharField(choices=[('draft', 'draft'), ('noindex', 'noindex'), ('indexable', 'indexable')], default=apps.seo.indexability.IndexabilityStatus['DRAFT'], max_length=16)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_path', models.CharField(blank=True, max_length=512)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('methodology_version', models.CharField(blank=True, max_length=64)),
                ('allow_schema', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('profile_status', models.CharField(choices=[('unclaimed', 'unclaimed'), ('claimed', 'claimed'), ('verified', 'verified'), ('disputed', 'disputed')], default='unclaimed', max_length=24)),
                ('short_description', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_service_links', to='locations.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='companies.company')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_service_links', to='services.service')),
            ],
            options={
                'ordering': ['company__name', 'city__name', 'service__name'],
                'constraints': [models.UniqueConstraint(fields=('company', 'city', 'service'), name='unique_company_city_service')],
            },
        ),
    ]
