# Generated by Django 5.2.15 on 2026-06-11 17:23

import apps.qr.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRReviewFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.SlugField(default=apps.qr.models.generate_qr_token, max_length=64, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('sentiment_filter_enabled', models.BooleanField(default=False)),
                ('scan_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_review_flows', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='QRScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent_family', models.CharField(blank=True, max_length=120)),
                ('visitor_ip_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_events', to='qr.qrreviewflow')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewPlatformLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('otzoviki', 'Otzoviki'), ('yandex', 'Yandex'), ('2gis', '2GIS'), ('google', 'Google'), ('other', 'Other')], max_length=16)),
                ('capability', models.CharField(choices=[('direct_form', 'Direct form'), ('profile', 'Profile'), ('manual', 'Manual'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('url', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to='qr.qrreviewflow')),
            ],
            options={
                'ordering': ['flow__company__name', 'platform'],
                'constraints': [models.UniqueConstraint(fields=('flow', 'platform'), name='unique_qr_platform_per_flow')],
            },
        ),
    ]
