# Generated by Django 5.2.15 on 2026-06-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebmasterSetupTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('yandex', 'Yandex Webmaster'), ('google', 'Google Search Console')], db_index=True, max_length=24)),
                ('task_key', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('done', 'Done'), ('blocked', 'Blocked')], db_index=True, default='todo', max_length=24)),
                ('verification_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['platform', 'task_key'],
                'indexes': [models.Index(fields=['platform', 'status'], name='launchqa_we_platfor_f7972c_idx')],
                'constraints': [models.UniqueConstraint(fields=('platform', 'task_key'), name='unique_webmaster_setup_task')],
            },
        ),
    ]
