# Generated by Django 5.2.15 on 2026-06-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchqa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchQACheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('routes', 'Routes and status codes'), ('indexability', 'Canonicals and robots meta'), ('schema', 'Schema matches visible content'), ('sitemap_robots', 'Sitemap and robots.txt'), ('mobile_cwv', 'Mobile and CWV basics'), ('content', 'Content quality')], db_index=True, max_length=32)),
                ('check_key', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=240)),
                ('target', models.CharField(blank=True, max_length=300)),
                ('expected', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To do'), ('passed', 'Passed'), ('failed', 'Failed'), ('blocked', 'Blocked')], db_index=True, default='todo', max_length=24)),
                ('evidence', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'check_key'],
                'indexes': [models.Index(fields=['category', 'status'], name='launchqa_la_categor_547d1f_idx')],
                'constraints': [models.UniqueConstraint(fields=('category', 'check_key'), name='unique_launch_qa_check')],
            },
        ),
    ]
