# Generated by Django 5.2.15 on 2026-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launchqa', '0002_launchqacheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexingMonitorURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('page_type', models.CharField(db_index=True, max_length=80)),
                ('index_status', models.CharField(choices=[('discovered', 'Discovered'), ('submitted', 'Submitted'), ('indexed', 'Indexed'), ('noindex', 'Noindex'), ('excluded', 'Excluded'), ('error', 'Error')], db_index=True, default='discovered', max_length=32)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_empty_profile', models.BooleanField(db_index=True, default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['page_type', 'url'],
                'indexes': [models.Index(fields=['index_status', 'is_empty_profile'], name='launchqa_in_index_s_9d9cc3_idx')],
            },
        ),
    ]
