# Generated by Django 5.2.15 on 2026-06-11 17:25

import apps.seo.indexability
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editorial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'guide categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_status', models.CharField(choices=[('draft', 'draft'), ('noindex', 'noindex'), ('indexable', 'indexable')], default=apps.seo.indexability.IndexabilityStatus['DRAFT'], max_length=16)),
                ('seo_title', models.CharField(blank=True, max_length=255)),
                ('seo_description', models.TextField(blank=True)),
                ('canonical_path', models.CharField(blank=True, max_length=512)),
                ('source_count', models.PositiveIntegerField(default=0)),
                ('methodology_version', models.CharField(blank=True, max_length=64)),
                ('allow_schema', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='editorial.author')),
                ('methodology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='editorial.methodologyversion')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guides', to='guides.guidecategory')),
            ],
            options={
                'ordering': ['-published_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GuideChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('text', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='guides.guide')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.CharField(max_length=260)),
                ('answer', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='guides.guide')),
            ],
            options={
                'verbose_name': 'guide FAQ',
                'verbose_name_plural': 'guide FAQs',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideInternalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('url', models.CharField(max_length=300)),
                ('target_type', models.CharField(choices=[('company', 'Company'), ('city_service', 'City service'), ('ranking', 'Ranking'), ('price', 'Price'), ('guide', 'Guide'), ('other', 'Other')], default='other', max_length=24)),
                ('position', models.PositiveIntegerField(default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_links', to='guides.guide')),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
        migrations.CreateModel(
            name='GuideRiskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('risk', models.CharField(max_length=240)),
                ('mitigation', models.TextField()),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_items', to='guides.guide')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GuideSourceReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=240)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('policy', 'Policy'), ('law', 'Law'), ('data', 'Data'), ('editorial', 'Editorial'), ('other', 'Other')], default='other', max_length=16)),
                ('position', models.PositiveIntegerField(default=0)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_references', to='guides.guide')),
            ],
            options={
                'ordering': ['position', 'label'],
            },
        ),
    ]
