import pytest
from django.contrib.auth import get_user_model


RELEASE_READINESS_100_GATES = [
    "100-gate release readiness JSON",
    "Staff-only release readiness endpoint",
    "Stable release schema",
    "Versioned release payload",
    "Generated by launch QA",
    "Aggregates blocker JSON",
    "Aggregates live runner summary",
    "Aggregates route smoke sources",
    "Go decision present",
    "No-go reasons present",
    "Launch status green when zero blockers",
    "Launch status red when blockers exist",
    "Yandex submit decision",
    "Google submit decision",
    "Sitemap submit decision",
    "IndexNow submit decision",
    "AI docs publish decision",
    "Public release decision",
    "Admin release decision",
    "Business workspace decision",
    "Manual release required",
    "Post-deploy smoke required",
    "Production credentials not required",
    "No deploy side effect",
    "No external network side effect",
    "GET-only readiness probe",
    "No mutation readiness probe",
    "Safe for cron context",
    "Safe for CI context",
    "Safe for Telegram summary",
    "Source ops hub link",
    "Source blocker dashboard link",
    "Source blocker JSON link",
    "Source live runner link",
    "Source route-smoke HTML link",
    "Source route-smoke JSON link",
    "Source route-smoke CSV link",
    "Probe count exported",
    "Passed count exported",
    "Failed count exported",
    "Failed paths exported",
    "Launch blocker count exported",
    "Result inventory exported",
    "Result snippets exported",
    "Response bytes exported",
    "Status code inventory exported",
    "Content type inventory exported",
    "Robots marker inventory exported",
    "Critical path list exported",
    "Public path list exported",
    "Private path list exported",
    "Admin path list exported",
    "Machine readable path list exported",
    "Indexable submit paths exported",
    "Noindex held paths exported",
    "Manual action list exported",
    "Yandex manual action exported",
    "Google manual action exported",
    "Sitemap manual action exported",
    "IndexNow manual action exported",
    "Post-deploy smoke action exported",
    "Rollback action exported",
    "Owner field exported",
    "Severity field exported",
    "Release phase field exported",
    "MVP launch cut field exported",
    "Yandex-first strategy marker",
    "Kazakhstan construction context marker",
    "Paid neutrality marker",
    "Right-of-reply marker",
    "Private evidence marker",
    "Review schema marker",
    "AggregateRating marker",
    "Canonical marker",
    "Breadcrumb marker",
    "JSON-LD marker",
    "Sitemap eligibility marker",
    "Robots policy marker",
    "LLMS docs marker",
    "AI reputation docs marker",
    "Business dashboard marker",
    "Claim-profile marker",
    "Reputation-audit marker",
    "Search noindex marker",
    "QR noindex marker",
    "Admin noindex marker",
    "Keyword admin marker",
    "AI evidence admin marker",
    "Launch QA admin marker",
    "Freshness dashboard marker",
    "Indexing monitor marker",
    "Webmaster checklist marker",
    "SEO audit export marker",
    "Route smoke matrix marker",
    "Blocker dashboard marker",
    "Blocker JSON marker",
    "Release readiness linked from ops hub",
    "Release readiness linked from blocker dashboard",
    "Release readiness linked from route smoke matrix",
    "Next 100-gate deployment handoff queue",
]


@pytest.mark.django_db
def test_release_readiness_json_requires_staff(client):
    response = client.get("/admin/launch-qa/release-readiness.json")

    assert response.status_code == 302
    assert "/admin/login/" in response["Location"]


@pytest.mark.django_db
def test_release_readiness_json_returns_100_gate_go_no_go_contract(client):
    staff = get_user_model().objects.create_user(username="release-readiness", password="pass", is_staff=True)
    client.force_login(staff)

    response = client.get("/admin/launch-qa/release-readiness.json")

    assert response.status_code == 200
    assert response["Content-Type"] == "application/json"
    payload = response.json()
    assert payload["schema"] == "otzoviki.release_readiness.v1"
    assert payload["version"] == "100-gate-release-readiness"
    assert payload["staff_only"] is True
    assert payload["robots"] == "noindex,follow"
    assert payload["count"] == 100
    assert payload["generated_by"] == "launchqa.release_readiness_json"
    assert payload["release_phase"] == "mvp-launch-cut"
    assert payload["strategy"] == "Yandex-first Kazakhstan construction/reputation SEO"
    assert payload["production_credentials_required"] is False
    assert payload["external_network_used"] is False
    assert payload["mutates_state"] is False
    assert payload["method"] == "GET"
    assert payload["sources"] == {
        "ops_hub": "/admin/launch-qa/",
        "blocker_dashboard": "/admin/launch-qa/blockers/",
        "blocker_json": "/admin/launch-qa/blockers.json",
        "live_runner": "/admin/launch-qa/route-smoke-live.json",
        "route_smoke_html": "/admin/launch-qa/route-smoke/",
        "route_smoke_json": "/admin/launch-qa/route-smoke.json",
        "route_smoke_csv": "/admin/launch-qa/route-smoke-export.csv",
    }
    summary = payload["summary"]
    assert summary["probe_count"] >= 14
    assert summary["failed"] == 0
    assert summary["launch_blocker_count"] == 0
    assert payload["go_no_go"]["status"] == "go"
    assert payload["go_no_go"]["no_go_reasons"] == []
    for key in [
        "yandex_submit_allowed",
        "google_submit_allowed",
        "sitemap_submit_allowed",
        "indexnow_allowed",
        "ai_docs_allowed",
        "public_release_allowed",
        "admin_release_allowed",
        "business_workspace_allowed",
    ]:
        assert payload["go_no_go"][key] is True, key
    assert payload["go_no_go"]["manual_release_required"] is True
    assert payload["go_no_go"]["post_deploy_smoke_required"] is True
    assert isinstance(payload["manual_actions"], list)
    for action in [
        "Run post-deploy route smoke live runner",
        "Submit green sitemap to Yandex Webmaster",
        "Submit green sitemap to Google Search Console",
        "Run IndexNow only after green state",
        "Keep blockers.json private/staff-only",
        "Rollback or hold release if any blocker appears",
    ]:
        assert action in payload["manual_actions"]
    assert len(payload["gates"]) == 100
    assert payload["gates"][0] == "100-gate release readiness JSON"
    assert payload["gates"][-1] == "Next 100-gate deployment handoff queue"
    for marker in RELEASE_READINESS_100_GATES:
        assert marker in payload["gates"], marker
    assert isinstance(payload["results"], list)
    assert payload["results"]
    assert all("path" in result and "passed" in result and "launch_blocker" in result for result in payload["results"])
    inventory = payload["inventory"]
    for key in [
        "critical_paths",
        "public_paths",
        "private_paths",
        "admin_paths",
        "machine_readable_paths",
        "indexable_submit_paths",
        "noindex_held_paths",
    ]:
        assert isinstance(inventory[key], list), key
    assert "/" in inventory["public_paths"]
    assert "/admin/launch-qa/blockers.json" in inventory["admin_paths"]
    assert "/sitemap.xml" in inventory["machine_readable_paths"]


@pytest.mark.django_db
def test_release_readiness_is_linked_from_ops_blockers_and_route_smoke(client):
    staff = get_user_model().objects.create_user(username="release-readiness-link", password="pass", is_staff=True)
    client.force_login(staff)

    for path in ["/admin/launch-qa/", "/admin/launch-qa/blockers/", "/admin/launch-qa/route-smoke/"]:
        response = client.get(path)
        assert response.status_code == 200
        assert "/admin/launch-qa/release-readiness.json" in response.content.decode()
