# Generated by Django 5.2.15 on 2026-06-11 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIYandexEvidenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('yandex_search', 'Yandex Search'), ('yandex_neuro', 'Yandex Neuro'), ('alice', 'Alice'), ('ai_overview', 'AI Overview'), ('other', 'Other')], max_length=32)),
                ('query', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=160)),
                ('answer_excerpt', models.TextField(blank=True)),
                ('cited_sources', models.JSONField(blank=True, default=list)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('mixed', 'Mixed'), ('negative', 'Negative'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('admin_only', 'Admin only')], default='private', max_length=16)),
                ('screenshot', models.FileField(blank=True, upload_to='ai-evidence/')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_yandex_evidence_logs', to='companies.company')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['company', 'platform', 'region'], name='ai_evidence_company_a2db5f_idx')],
            },
        ),
    ]
