# Generated by Django 5.2.15 on 2026-06-11 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('normalized_query', models.CharField(blank=True, db_index=True, max_length=500)),
                ('frequency', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('keys_so', 'Keys.so'), ('manual', 'Manual'), ('other', 'Other')], default='keys_so', max_length=32)),
                ('region', models.CharField(blank=True, max_length=32)),
                ('target_cluster', models.CharField(blank=True, db_index=True, max_length=180)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-frequency', 'normalized_query'],
                'indexes': [models.Index(fields=['source', 'region'], name='keywords_ke_source_262aed_idx')],
            },
        ),
        migrations.CreateModel(
            name='KeywordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('intent', models.CharField(choices=[('commercial', 'Commercial'), ('navigational', 'Navigational'), ('informational', 'Informational'), ('mixed', 'Mixed')], default='mixed', max_length=32)),
                ('page_type', models.CharField(blank=True, max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keywords', models.ManyToManyField(blank=True, related_name='clusters', to='keywords.keyword')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='KeywordPageMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('company_dossier', 'Company dossier'), ('city_service', 'City service'), ('ranking', 'Ranking'), ('price', 'Price'), ('city_hub', 'City hub'), ('guide', 'Guide'), ('other', 'Other')], max_length=48)),
                ('canonical_pattern', models.CharField(max_length=300)),
                ('priority', models.CharField(choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('later', 'Later')], default='P1', max_length=16)),
                ('is_indexable_candidate', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_maps', to='keywords.keywordcluster')),
            ],
            options={
                'ordering': ['priority', 'page_type', 'cluster__slug'],
                'constraints': [models.UniqueConstraint(fields=('cluster', 'page_type', 'canonical_pattern'), name='unique_keyword_page_map')],
            },
        ),
        migrations.CreateModel(
            name='KeywordURLCompetitorEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('domain', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('h1', models.CharField(blank=True, max_length=500)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_evidence', to='keywords.keyword')),
            ],
            options={
                'ordering': ['keyword__normalized_query', 'position', 'domain'],
                'indexes': [models.Index(fields=['domain', 'position'], name='keywords_ke_domain_6ba0e1_idx')],
            },
        ),
    ]
