from collections import defaultdict
import csv

from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render
from django.test import Client
from django.utils import timezone

from apps.companies.models import Company
from apps.evidence.models import ExternalSource
from apps.guides.models import Guide

from .models import (
    IndexingMonitorURL,
    LaunchQACheck,
    WebmasterSetupTask,
    ensure_default_launch_qa_checks,
    ensure_default_webmaster_tasks,
)


OPS_100_GATES = [
    "100-gate launch operations hub",
    "Staff-only operations surface",
    "Robots: noindex,follow",
    "Launch QA checklist",
    "Indexing monitor",
    "Freshness dashboard",
    "Webmaster checklist",
    "SEO audit CSV export",
    "Keyword/page mapping report",
    "Keyword page-map CSV export",
    "AI evidence capture",
    "Admin moderation index",
    "Review moderation queue",
    "Official response moderation queue",
    "Claim profile moderation queue",
    "Reputation audit leads",
    "Business representative verification",
    "Company indexability review",
    "Company freshness review",
    "Private proof audit",
    "Evidence visibility audit",
    "Rating snapshot rebuild check",
    "Sitemap inclusion audit",
    "Robots policy audit",
    "LLMS public docs audit",
    "AI reputation docs audit",
    "Yandex-first readiness",
    "Google Search Console readiness",
    "Bing/AI crawler readiness",
    "Sitemap submission status",
    "Manual indexing queue",
    "Coverage diagnostics",
    "Submitted URL inventory",
    "Indexed URL inventory",
    "Noindex URL inventory",
    "Empty profile suppression",
    "HTTP 404/5xx launch risk",
    "Indexed empty profile risk",
    "Submitted noindex risk",
    "Canonical mismatch risk",
    "Schema parity risk",
    "AggregateRating safety",
    "Review schema safety",
    "Public-only evidence safety",
    "Private/admin-only evidence safety",
    "Paid profile neutrality",
    "No review deletion privilege",
    "No rating override privilege",
    "No indexing override privilege",
    "Official response separation",
    "Right-of-reply policy",
    "Claim profile approval audit",
    "Official response publish audit",
    "Reputation audit output audit",
    "Same-host source attribution",
    "External referer suppression",
    "Query/fragment stripping",
    "B2B verified identity source",
    "POST identity spoof protection",
    "Anonymous representative spoof protection",
    "Pending representative action lock",
    "Unverified email action lock",
    "Managed company actions",
    "Private workspace noindex",
    "Business dashboard live probe",
    "Company dossier live probe",
    "Guides hub live probe",
    "Guide detail quality gate",
    "Policy pages live probe",
    "Claim-profile form noindex",
    "Reputation-audit form noindex",
    "Official-response form noindex",
    "Review submission form noindex",
    "Search results noindex",
    "QR routes noindex",
    "Launch route smoke matrix",
    "Status code matrix",
    "Canonical matrix",
    "BreadcrumbList matrix",
    "JSON-LD validity matrix",
    "Mobile/CWV basics",
    "Thin-page suppression",
    "Low-quality guide suppression",
    "Draft guide suppression",
    "Draft company suppression",
    "Stale dossier worklist",
    "Stale source worklist",
    "Stale guide worklist",
    "90-day trust cutoff",
    "Yandex/AI evidence recrawl",
    "Methodology version drift",
    "Content source requirements",
    "Money-page internal links",
    "Checklist/risk/FAQ guide quality",
    "Stage 4A keyword coverage",
    "Markin page-map alignment",
    "Hybrid matrix P0/P1 coverage",
    "E-E-A-T trust gates",
    "CIS CDN fallback readiness",
    "Launch blocker summary",
    "Next 100-gate batch queue",
]


ROUTE_SMOKE_ROUTES = [
    ("Home", "/", "200", "index,follow", "canonical + BreadcrumbList"),
    ("KZ root", "/kz/", "200", "index,follow", "canonical + BreadcrumbList"),
    ("City hub", "/kz/almaty/", "200", "data-dependent", "empty noindex; populated index"),
    ("City service", "/kz/almaty/remont-kvartir/", "200", "data-dependent", "empty noindex; populated index"),
    ("Ranking", "/kz/almaty/reyting-remontnyh-kompaniy/", "200", "data-dependent", "rating safety"),
    ("Price", "/kz/almaty/remont-kvartir/ceny/", "200", "data-dependent", "non-offer caveat"),
    ("Company dossier", "/kz/company/{slug}/", "200", "trust-gated", "schema only when safe"),
    ("Review submission", "/kz/company/{slug}/reviews/new/", "200", "noindex,follow", "form route excluded"),
    ("Official response", "/kz/company/{slug}/official-response/new/", "200", "noindex,follow", "identity safety"),
    ("Guides hub", "/kz/guides/", "200", "data-dependent", "empty noindex; populated index"),
    ("Methodology", "/methodology/", "200", "index,follow", "policy route"),
    ("Review policy", "/review-policy/", "200", "index,follow", "policy route"),
    ("Right-of-reply", "/right-of-reply/", "200", "index,follow", "policy route"),
    ("Privacy", "/privacy/", "200", "index,follow", "policy route"),
    ("Terms", "/terms/", "200", "index,follow", "policy route"),
    ("For business", "/for-business/", "200", "index,follow", "neutrality disclosure"),
    ("Claim profile", "/claim-profile/", "200", "noindex,follow", "lead form route"),
    ("Reputation audit", "/reputation-audit/", "200", "noindex,follow", "lead form route"),
    ("Business dashboard", "/business/dashboard/", "302/200", "noindex,follow", "auth required"),
    ("Search", "/search/", "200", "noindex,follow", "excluded from sitemap"),
    ("Robots", "/robots.txt", "200", "text/plain", "crawler policy"),
    ("Sitemap", "/sitemap.xml", "200", "application/xml", "indexable canonical only"),
    ("LLMS", "/llms.txt", "200", "text/plain", "AI public docs"),
    ("AI reputation", "/ai-reputation.md", "200", "text/markdown", "AI/Yandex policy"),
    ("Launch ops", "/admin/launch-qa/", "302/200", "noindex,follow", "staff-only"),
    ("Route smoke matrix", "/admin/launch-qa/route-smoke/", "302/200", "noindex,follow", "staff-only"),
    ("Route smoke CSV export", "/admin/launch-qa/route-smoke-export.csv", "302/200", "text/csv", "staff-only"),
]

ROUTE_SMOKE_CSV_FIELDS = [
    "gate_number",
    "gate",
    "route_label",
    "path_pattern",
    "expected_status",
    "expected_robots",
    "expected_content_type",
    "auth_requirement",
    "canonical_requirement",
    "schema_requirement",
    "sitemap_requirement",
    "launch_risk_if_fails",
    "manual_probe_note",
]

ROUTE_SMOKE_CSV_GATES = [
    "100-gate route smoke CSV export",
    "Staff-only CSV export",
    "Yandex submit only green routes",
    "Google submit only green routes",
    "Noindex routes excluded from sitemap",
    "Private/admin routes excluded from sitemap",
    "Canonical has no query or fragment",
    "Schema only when visible evidence supports it",
    "Paid profile neutrality must be visible",
    "Manual post-deploy probe required",
    "Home route CSV row",
    "KZ root CSV row",
    "City hub CSV row",
    "City service CSV row",
    "Ranking CSV row",
    "Price CSV row",
    "Company dossier CSV row",
    "Company review submission CSV row",
    "Company official response CSV row",
    "Guides hub CSV row",
    "Guide detail CSV row",
    "Methodology CSV row",
    "Review policy CSV row",
    "Right-of-reply CSV row",
    "Privacy CSV row",
    "Terms CSV row",
    "For-business CSV row",
    "Claim-profile CSV row",
    "Reputation-audit CSV row",
    "Business dashboard CSV row",
    "Search CSV row",
    "Search autocomplete CSV row",
    "QR landing CSV row",
    "QR platform click CSV row",
    "Robots txt CSV row",
    "Sitemap XML CSV row",
    "LLMS TXT CSV row",
    "AI reputation markdown CSV row",
    "Launch ops hub CSV row",
    "Route smoke matrix CSV row",
    "Launch QA checklist CSV row",
    "Indexing monitor CSV row",
    "Freshness dashboard CSV row",
    "Webmaster checklist CSV row",
    "SEO audit export CSV row",
    "Keyword report CSV row",
    "Keyword page-map export CSV row",
    "AI evidence capture CSV row",
    "Admin index CSV row",
    "Admin model queues CSV row",
    "Status code expectation column",
    "Robots expectation column",
    "Content-Type expectation column",
    "Auth requirement column",
    "Canonical requirement column",
    "Schema requirement column",
    "Sitemap requirement column",
    "Launch risk column",
    "Manual probe note column",
    "Indexable public route marker",
    "Noindex private route marker",
    "Noindex form route marker",
    "Machine-readable route marker",
    "Staff-only route marker",
    "Redirect route marker",
    "JSON route marker",
    "Canonical required marker",
    "Canonical not applicable marker",
    "Breadcrumb required marker",
    "JSON-LD required marker",
    "AggregateRating safety marker",
    "Review schema safety marker",
    "Public evidence safety marker",
    "Private evidence safety marker",
    "Paid profile neutrality marker",
    "Right-of-reply marker",
    "B2B identity marker",
    "Moderation queue marker",
    "Sitemap include marker",
    "Sitemap exclude marker",
    "Robots allow marker",
    "Robots disallow marker",
    "Yandex Webmaster queue marker",
    "Google Search Console queue marker",
    "AI crawler docs marker",
    "Empty profile suppression marker",
    "Draft guide suppression marker",
    "Low-quality guide suppression marker",
    "Search exclusion marker",
    "QR exclusion marker",
    "Admin exclusion marker",
    "Lead form exclusion marker",
    "Official response exclusion marker",
    "Review form exclusion marker",
    "Manual deploy smoke owner marker",
    "Post-deploy timestamp marker",
    "Export filename marker",
    "CSV UTF-8 marker",
    "Stable row count marker",
    "Next route-smoke import queue",
]

DEPLOYMENT_JSON_GATES = [
    '100-gate deployment handoff JSON export',
    'Staff-only deployment JSON',
    'Stable deployment JSON schema',
    'Versioned deployment JSON payload',
    'Generated deployment metadata',
    'Release readiness embedded',
    'Go/no-go embedded',
    'Manual actions embedded',
    'Source links embedded',
    'Inventory embedded',
    'Pre-deploy checklist JSON',
    'Deploy checklist JSON',
    'Post-deploy checklist JSON',
    'Search submission checklist JSON',
    'Rollback checklist JSON',
    'Monitoring checklist JSON',
    'Yandex submit gate JSON',
    'Google submit gate JSON',
    'IndexNow gate JSON',
    'Sitemap submit gate JSON',
    'AI docs gate JSON',
    'Public release gate JSON',
    'Admin release gate JSON',
    'Business workspace gate JSON',
    'Manual release required JSON',
    'Post-deploy smoke required JSON',
    'Production credentials false JSON',
    'External network false JSON',
    'Mutates state false JSON',
    'GET method JSON',
    'Health probe action JSON',
    'Route smoke live action JSON',
    'Release readiness verify action JSON',
    'Yandex Webmaster action JSON',
    'Google Search Console action JSON',
    'IndexNow action JSON',
    'Rollback if blockers JSON',
    'Rollback if 5xx JSON',
    'Rollback if sitemap malformed JSON',
    'Rollback if robots blocks docs JSON',
    'Rollback if private noindex missing JSON',
    'Rollback if schema unsafe JSON',
    'Rollback if paid neutrality missing JSON',
    'Rollback if review forms indexable JSON',
    'Rollback if business dashboard public JSON',
    'Monitoring first hour JSON',
    'Monitoring first day JSON',
    'Yandex crawl monitoring JSON',
    'Google crawl monitoring JSON',
    'Server logs monitoring JSON',
    'Django errors monitoring JSON',
    '404/500 monitoring JSON',
    'Sitemap fetch monitoring JSON',
    'Robots fetch monitoring JSON',
    'LLMS fetch monitoring JSON',
    'AI reputation fetch monitoring JSON',
    'Critical paths inventory JSON',
    'Public paths inventory JSON',
    'Private paths inventory JSON',
    'Admin paths inventory JSON',
    'Machine-readable paths inventory JSON',
    'Indexable submit paths inventory JSON',
    'Noindex held paths inventory JSON',
    'Ops hub source JSON',
    'Deployment handoff HTML source JSON',
    'Release readiness source JSON',
    'Blockers JSON source JSON',
    'Blockers HTML source JSON',
    'Route smoke live source JSON',
    'Route smoke JSON source JSON',
    'Route smoke CSV source JSON',
    'No public exposure JSON',
    'No sitemap inclusion JSON',
    'Private cache safe JSON',
    'CI adapter ready JSON',
    'Cron adapter ready JSON',
    'Post-deploy automation ready JSON',
    'Manual owner required JSON',
    'Timestamp placeholder JSON',
    'Environment placeholder JSON',
    'Revision placeholder JSON',
    'Deploy actor placeholder JSON',
    'Yandex-first strategy JSON',
    'Kazakhstan construction SEO JSON',
    'Trust and neutrality JSON',
    'Evidence privacy JSON',
    'Schema safety JSON',
    'B2B identity safety JSON',
    'Review moderation safety JSON',
    'Official response safety JSON',
    'Claim profile safety JSON',
    'Freshness worklist safety JSON',
    'Indexing monitor safety JSON',
    'Webmaster checklist safety JSON',
    'Keyword map safety JSON',
    'AI evidence safety JSON',
    'Launch blockers linked JSON',
    'Deployment CSV linked JSON',
    'Deployment live linked JSON',
    'Next 300-gate production adapter queue',
]

DEPLOYMENT_CSV_GATES = [
    '100-gate deployment handoff CSV export',
    'Staff-only deployment CSV',
    'Stable deployment CSV schema',
    'Versioned deployment CSV payload',
    'Generated deployment metadata',
    'Release readiness embedded',
    'Go/no-go embedded',
    'Manual actions embedded',
    'Source links embedded',
    'Inventory embedded',
    'Pre-deploy checklist CSV',
    'Deploy checklist CSV',
    'Post-deploy checklist CSV',
    'Search submission checklist CSV',
    'Rollback checklist CSV',
    'Monitoring checklist CSV',
    'Yandex submit gate CSV',
    'Google submit gate CSV',
    'IndexNow gate CSV',
    'Sitemap submit gate CSV',
    'AI docs gate CSV',
    'Public release gate CSV',
    'Admin release gate CSV',
    'Business workspace gate CSV',
    'Manual release required CSV',
    'Post-deploy smoke required CSV',
    'Production credentials false CSV',
    'External network false CSV',
    'Mutates state false CSV',
    'GET method CSV',
    'Health probe action CSV',
    'Route smoke live action CSV',
    'Release readiness verify action CSV',
    'Yandex Webmaster action CSV',
    'Google Search Console action CSV',
    'IndexNow action CSV',
    'Rollback if blockers CSV',
    'Rollback if 5xx CSV',
    'Rollback if sitemap malformed CSV',
    'Rollback if robots blocks docs CSV',
    'Rollback if private noindex missing CSV',
    'Rollback if schema unsafe CSV',
    'Rollback if paid neutrality missing CSV',
    'Rollback if review forms indexable CSV',
    'Rollback if business dashboard public CSV',
    'Monitoring first hour CSV',
    'Monitoring first day CSV',
    'Yandex crawl monitoring CSV',
    'Google crawl monitoring CSV',
    'Server logs monitoring CSV',
    'Django errors monitoring CSV',
    '404/500 monitoring CSV',
    'Sitemap fetch monitoring CSV',
    'Robots fetch monitoring CSV',
    'LLMS fetch monitoring CSV',
    'AI reputation fetch monitoring CSV',
    'Critical paths inventory CSV',
    'Public paths inventory CSV',
    'Private paths inventory CSV',
    'Admin paths inventory CSV',
    'Machine-readable paths inventory CSV',
    'Indexable submit paths inventory CSV',
    'Noindex held paths inventory CSV',
    'Ops hub source CSV',
    'Deployment handoff HTML source CSV',
    'Release readiness source CSV',
    'Blockers CSV source CSV',
    'Blockers HTML source CSV',
    'Route smoke live source CSV',
    'Route smoke CSV source CSV',
    'Route smoke CSV source CSV',
    'No public exposure CSV',
    'No sitemap inclusion CSV',
    'Private cache safe CSV',
    'CI adapter ready CSV',
    'Cron adapter ready CSV',
    'Post-deploy automation ready CSV',
    'Manual owner required CSV',
    'Timestamp placeholder CSV',
    'Environment placeholder CSV',
    'Revision placeholder CSV',
    'Deploy actor placeholder CSV',
    'Yandex-first strategy CSV',
    'Kazakhstan construction SEO CSV',
    'Trust and neutrality CSV',
    'Evidence privacy CSV',
    'Schema safety CSV',
    'B2B identity safety CSV',
    'Review moderation safety CSV',
    'Official response safety CSV',
    'Claim profile safety CSV',
    'Freshness worklist safety CSV',
    'Indexing monitor safety CSV',
    'Webmaster checklist safety CSV',
    'Keyword map safety CSV',
    'AI evidence safety CSV',
    'Launch blockers linked CSV',
    'Deployment CSV linked CSV',
    'Deployment live linked CSV',
    'Next 300-gate production adapter queue',
]

DEPLOYMENT_LIVE_GATES = [
    '100-gate deployment handoff live export',
    'Staff-only deployment LIVE',
    'Stable deployment LIVE schema',
    'Versioned deployment LIVE payload',
    'Generated deployment metadata',
    'Release readiness embedded',
    'Go/no-go embedded',
    'Manual actions embedded',
    'Source links embedded',
    'Inventory embedded',
    'Pre-deploy checklist LIVE',
    'Deploy checklist LIVE',
    'Post-deploy checklist LIVE',
    'Search submission checklist LIVE',
    'Rollback checklist LIVE',
    'Monitoring checklist LIVE',
    'Yandex submit gate LIVE',
    'Google submit gate LIVE',
    'IndexNow gate LIVE',
    'Sitemap submit gate LIVE',
    'AI docs gate LIVE',
    'Public release gate LIVE',
    'Admin release gate LIVE',
    'Business workspace gate LIVE',
    'Manual release required LIVE',
    'Post-deploy smoke required LIVE',
    'Production credentials false LIVE',
    'External network false LIVE',
    'Mutates state false LIVE',
    'GET method LIVE',
    'Health probe action LIVE',
    'Route smoke live action LIVE',
    'Release readiness verify action LIVE',
    'Yandex Webmaster action LIVE',
    'Google Search Console action LIVE',
    'IndexNow action LIVE',
    'Rollback if blockers LIVE',
    'Rollback if 5xx LIVE',
    'Rollback if sitemap malformed LIVE',
    'Rollback if robots blocks docs LIVE',
    'Rollback if private noindex missing LIVE',
    'Rollback if schema unsafe LIVE',
    'Rollback if paid neutrality missing LIVE',
    'Rollback if review forms indexable LIVE',
    'Rollback if business dashboard public LIVE',
    'Monitoring first hour LIVE',
    'Monitoring first day LIVE',
    'Yandex crawl monitoring LIVE',
    'Google crawl monitoring LIVE',
    'Server logs monitoring LIVE',
    'Django errors monitoring LIVE',
    '404/500 monitoring LIVE',
    'Sitemap fetch monitoring LIVE',
    'Robots fetch monitoring LIVE',
    'LLMS fetch monitoring LIVE',
    'AI reputation fetch monitoring LIVE',
    'Critical paths inventory LIVE',
    'Public paths inventory LIVE',
    'Private paths inventory LIVE',
    'Admin paths inventory LIVE',
    'Machine-readable paths inventory LIVE',
    'Indexable submit paths inventory LIVE',
    'Noindex held paths inventory LIVE',
    'Ops hub source LIVE',
    'Deployment handoff HTML source LIVE',
    'Release readiness source LIVE',
    'Blockers LIVE source LIVE',
    'Blockers HTML source LIVE',
    'Route smoke live source LIVE',
    'Route smoke LIVE source LIVE',
    'Route smoke CSV source LIVE',
    'No public exposure LIVE',
    'No sitemap inclusion LIVE',
    'Private cache safe LIVE',
    'CI adapter ready LIVE',
    'Cron adapter ready LIVE',
    'Post-deploy automation ready LIVE',
    'Manual owner required LIVE',
    'Timestamp placeholder LIVE',
    'Environment placeholder LIVE',
    'Revision placeholder LIVE',
    'Deploy actor placeholder LIVE',
    'Yandex-first strategy LIVE',
    'Kazakhstan construction SEO LIVE',
    'Trust and neutrality LIVE',
    'Evidence privacy LIVE',
    'Schema safety LIVE',
    'B2B identity safety LIVE',
    'Review moderation safety LIVE',
    'Official response safety LIVE',
    'Claim profile safety LIVE',
    'Freshness worklist safety LIVE',
    'Indexing monitor safety LIVE',
    'Webmaster checklist safety LIVE',
    'Keyword map safety LIVE',
    'AI evidence safety LIVE',
    'Launch blockers linked LIVE',
    'Deployment CSV linked LIVE',
    'Deployment live linked LIVE',
    'Next 300-gate production adapter queue',
]

DEPLOYMENT_CSV_FIELDS = [
    "gate_number",
    "gate",
    "section",
    "status",
    "allowed",
    "source_path",
    "manual_action",
    "launch_risk_if_fails",
]

DEPLOYMENT_HANDOFF_100_GATES = [
    '100-gate deployment handoff dashboard',
    'Staff-only deployment surface',
    'Robots: noindex,follow',
    'Canonical deployment handoff URL',
    'Release readiness source linked',
    'Blocker JSON source linked',
    'Blocker dashboard source linked',
    'Route smoke live source linked',
    'Route smoke JSON source linked',
    'Route smoke CSV source linked',
    'Ops hub source linked',
    'Go/no-go status visible',
    'Summary failed count visible',
    'Launch blocker count visible',
    'Manual release required visible',
    'Post-deploy smoke required visible',
    'Pre-deploy backup reminder',
    'Pre-deploy environment variable reminder',
    'Pre-deploy static collect reminder',
    'Pre-deploy migrations reminder',
    'Pre-deploy secrets not exposed reminder',
    'Pre-deploy DEBUG false reminder',
    'Pre-deploy ALLOWED_HOSTS reminder',
    'Pre-deploy CSRF trusted origins reminder',
    'Pre-deploy database connectivity reminder',
    'Deploy code revision reminder',
    'Deploy dependency install reminder',
    'Deploy migrate command reminder',
    'Deploy collectstatic command reminder',
    'Deploy restart app service reminder',
    'Deploy restart worker service reminder',
    'Deploy health endpoint reminder',
    'Deploy run route smoke live runner',
    'Deploy verify release readiness JSON',
    'Post-deploy home probe',
    'Post-deploy KZ root probe',
    'Post-deploy for-business probe',
    'Post-deploy claim-profile noindex probe',
    'Post-deploy reputation-audit noindex probe',
    'Post-deploy business dashboard auth probe',
    'Post-deploy robots.txt probe',
    'Post-deploy sitemap.xml probe',
    'Post-deploy llms.txt probe',
    'Post-deploy ai-reputation.md probe',
    'Post-deploy ops hub probe',
    'Post-deploy blockers probe',
    'Post-deploy release-readiness probe',
    'Yandex Webmaster submit only after green',
    'Google Search Console submit only after green',
    'IndexNow only after green',
    'Do not submit noindex URLs',
    'Do not submit admin URLs',
    'Do not submit search URLs',
    'Do not submit QR URLs',
    'Do not submit lead form URLs',
    'Do not submit private business URLs',
    'Sitemap only canonical indexable URLs',
    'Robots disallow admin launch QA',
    'Robots disallow keywords admin',
    'Robots disallow AI evidence admin',
    'Robots disallow business workspace',
    'Robots allow llms.txt',
    'Robots allow ai-reputation.md',
    'AI docs remain public',
    'Blockers JSON remains private',
    'Release readiness JSON remains private',
    'Route smoke exports remain private',
    'No production credentials in handoff',
    'No external publication by app',
    'No destructive data action',
    'Rollback if blockers appear',
    'Rollback if 5xx appears',
    'Rollback if sitemap is malformed',
    'Rollback if robots blocks public docs',
    'Rollback if noindex disappears from private routes',
    'Rollback if schema safety fails',
    'Rollback if paid neutrality copy missing',
    'Rollback if review forms indexable',
    'Rollback if business dashboard public',
    'Monitoring first hour reminder',
    'Monitoring first day reminder',
    'Yandex crawling observation reminder',
    'Google crawling observation reminder',
    'Server logs review reminder',
    'Django errors review reminder',
    '404/500 review reminder',
    'Sitemap fetch review reminder',
    'Robots fetch review reminder',
    'LLMS fetch review reminder',
    'AI reputation fetch review reminder',
    'Manual owner checklist visible',
    'Deployment command checklist visible',
    'Post-deploy smoke checklist visible',
    'Search submission checklist visible',
    'Rollback checklist visible',
    'Monitoring checklist visible',
    'Green release state visible',
    'Red hold state visible',
    'Next deployment JSON queue',
    'Next production cron queue',
]

RELEASE_READINESS_100_GATES = [
    '100-gate release readiness JSON',
    'Staff-only release readiness endpoint',
    'Stable release schema',
    'Versioned release payload',
    'Generated by launch QA',
    'Aggregates blocker JSON',
    'Aggregates live runner summary',
    'Aggregates route smoke sources',
    'Go decision present',
    'No-go reasons present',
    'Launch status green when zero blockers',
    'Launch status red when blockers exist',
    'Yandex submit decision',
    'Google submit decision',
    'Sitemap submit decision',
    'IndexNow submit decision',
    'AI docs publish decision',
    'Public release decision',
    'Admin release decision',
    'Business workspace decision',
    'Manual release required',
    'Post-deploy smoke required',
    'Production credentials not required',
    'No deploy side effect',
    'No external network side effect',
    'GET-only readiness probe',
    'No mutation readiness probe',
    'Safe for cron context',
    'Safe for CI context',
    'Safe for Telegram summary',
    'Source ops hub link',
    'Source blocker dashboard link',
    'Source blocker JSON link',
    'Source live runner link',
    'Source route-smoke HTML link',
    'Source route-smoke JSON link',
    'Source route-smoke CSV link',
    'Probe count exported',
    'Passed count exported',
    'Failed count exported',
    'Failed paths exported',
    'Launch blocker count exported',
    'Result inventory exported',
    'Result snippets exported',
    'Response bytes exported',
    'Status code inventory exported',
    'Content type inventory exported',
    'Robots marker inventory exported',
    'Critical path list exported',
    'Public path list exported',
    'Private path list exported',
    'Admin path list exported',
    'Machine readable path list exported',
    'Indexable submit paths exported',
    'Noindex held paths exported',
    'Manual action list exported',
    'Yandex manual action exported',
    'Google manual action exported',
    'Sitemap manual action exported',
    'IndexNow manual action exported',
    'Post-deploy smoke action exported',
    'Rollback action exported',
    'Owner field exported',
    'Severity field exported',
    'Release phase field exported',
    'MVP launch cut field exported',
    'Yandex-first strategy marker',
    'Kazakhstan construction context marker',
    'Paid neutrality marker',
    'Right-of-reply marker',
    'Private evidence marker',
    'Review schema marker',
    'AggregateRating marker',
    'Canonical marker',
    'Breadcrumb marker',
    'JSON-LD marker',
    'Sitemap eligibility marker',
    'Robots policy marker',
    'LLMS docs marker',
    'AI reputation docs marker',
    'Business dashboard marker',
    'Claim-profile marker',
    'Reputation-audit marker',
    'Search noindex marker',
    'QR noindex marker',
    'Admin noindex marker',
    'Keyword admin marker',
    'AI evidence admin marker',
    'Launch QA admin marker',
    'Freshness dashboard marker',
    'Indexing monitor marker',
    'Webmaster checklist marker',
    'SEO audit export marker',
    'Route smoke matrix marker',
    'Blocker dashboard marker',
    'Blocker JSON marker',
    'Release readiness linked from ops hub',
    'Release readiness linked from blocker dashboard',
    'Release readiness linked from route smoke matrix',
    'Next 100-gate deployment handoff queue',
]

LAUNCH_BLOCKER_JSON_100_GATES = [
    '100-gate launch blocker JSON export',
    'Staff-only blocker JSON',
    'Stable blocker schema name',
    'Versioned blocker payload',
    'Generated blocker metadata',
    'No external network blocker export',
    'GET-only blocker export',
    'No mutation blocker export',
    'No production credentials blocker export',
    'Live runner summary embedded',
    'Probe count field',
    'Passed count field',
    'Failed count field',
    'Failed paths field',
    'Launch blocker count field',
    'Green launch status field',
    'Red launch status field',
    'Yandex submit allowed boolean',
    'Google submit allowed boolean',
    'Sitemap submit allowed boolean',
    'IndexNow allowed boolean',
    'AI docs allowed boolean',
    'Public release allowed boolean',
    'Admin release allowed boolean',
    'Business workspace allowed boolean',
    'Manual release required boolean',
    'Post deploy smoke required boolean',
    'Source live runner link',
    'Source route smoke JSON link',
    'Source route smoke CSV link',
    'Source route smoke HTML link',
    'Source blocker HTML link',
    'Ops hub link',
    'Home result included',
    'KZ root result included',
    'For-business result included',
    'Claim-profile result included',
    'Reputation-audit result included',
    'Business dashboard redirect included',
    'Robots result included',
    'Sitemap result included',
    'LLMS result included',
    'AI reputation result included',
    'Launch ops result included',
    'Route smoke HTML result included',
    'Route smoke JSON result included',
    'Route smoke CSV result included',
    'Result status code preserved',
    'Result expected status preserved',
    'Result content type preserved',
    'Result expected content type preserved',
    'Result robots marker preserved',
    'Result passed boolean preserved',
    'Result launch blocker boolean preserved',
    'Result response bytes preserved',
    'Result redirect location preserved',
    'Result snippet preserved',
    'Blocker severity critical',
    'Blocker severity warning',
    'Blocker severity manual',
    'Action hold Yandex submit',
    'Action hold Google submit',
    'Action hold sitemap submit',
    'Action hold IndexNow ping',
    'Action verify robots',
    'Action verify sitemap',
    'Action verify AI docs',
    'Action verify private noindex',
    'Action verify lead forms noindex',
    'Action verify business redirect',
    'Action verify admin staff-only',
    'Action verify canonical',
    'Action verify schema',
    'Action verify evidence privacy',
    'Action verify paid neutrality',
    'Action verify right-of-reply',
    'Action verify B2B identity',
    'Action verify moderation queues',
    'Action verify freshness',
    'Action verify indexing monitor',
    'Action verify webmaster checklist',
    'Action verify keyword map',
    'Action verify AI evidence capture',
    'Action verify route smoke CSV',
    'Action verify route smoke JSON',
    'Action verify route smoke live',
    'Action verify blocker HTML',
    'CI-friendly blocker payload',
    'Cron-friendly blocker payload',
    'Post-deploy automation payload',
    'Machine-readable launch decision',
    'Manual owner next action',
    'Safe to cache privately',
    'Do not expose publicly',
    'No sitemap inclusion for blocker JSON',
    'No robots allow requirement for blocker JSON',
    'Blocker export linked from ops hub',
    'Blocker export linked from blocker dashboard',
    'Blocker export linked from route smoke matrix',
    'Next 100-gate release readiness queue',
]

LAUNCH_BLOCKER_100_GATES = [
    '100-gate launch blocker dashboard',
    'Staff-only blocker dashboard',
    'Robots: noindex,follow',
    'Canonical blocker dashboard URL',
    'Live runner summary',
    'Route smoke HTML link',
    'Route smoke JSON link',
    'Route smoke CSV link',
    'Route smoke live link',
    'Ops hub back link',
    'Yandex submit blocked if failures',
    'Google submit blocked if failures',
    'Sitemap submit blocked if failures',
    'AI crawler docs blocker check',
    'Robots policy blocker check',
    'Sitemap XML blocker check',
    'LLMS TXT blocker check',
    'AI reputation markdown blocker check',
    'Public home blocker check',
    'KZ root blocker check',
    'For-business blocker check',
    'Claim-profile noindex blocker check',
    'Reputation-audit noindex blocker check',
    'Business dashboard redirect blocker check',
    'Admin ops auth blocker check',
    'Route smoke matrix auth blocker check',
    'JSON export auth blocker check',
    'CSV export auth blocker check',
    'Status code failures visible',
    'Content-type failures visible',
    'Robots marker failures visible',
    'Redirect failures visible',
    'Failed paths list visible',
    'Passed count visible',
    'Failed count visible',
    'Probe count visible',
    'Launch blocker count visible',
    'Green launch state visible',
    'Red launch state visible',
    'Manual verification reminder',
    'No external network note',
    'GET-only probe note',
    'No mutation note',
    'No production credentials note',
    'Post-deploy required note',
    'Yandex Webmaster hold note',
    'Google Search Console hold note',
    'IndexNow hold note',
    'Sitemap submission hold note',
    'Public route release gate',
    'Private route release gate',
    'Admin route release gate',
    'Machine-readable release gate',
    'Policy page release gate',
    'Lead form release gate',
    'B2B workspace release gate',
    'Search noindex release gate',
    'QR noindex release gate',
    'Evidence privacy release gate',
    'Paid neutrality release gate',
    'Right-of-reply release gate',
    'Schema safety release gate',
    'AggregateRating release gate',
    'Review schema release gate',
    'Canonical release gate',
    'Breadcrumb release gate',
    'JSON-LD release gate',
    'Sitemap inclusion release gate',
    'Sitemap exclusion release gate',
    'Robots allow release gate',
    'Robots disallow release gate',
    'Empty profile suppression gate',
    'Draft guide suppression gate',
    'Low-quality guide suppression gate',
    'Admin launch QA suppression gate',
    'Keyword admin suppression gate',
    'AI evidence admin suppression gate',
    'Business workspace suppression gate',
    'Search suppression gate',
    'QR suppression gate',
    'Review form suppression gate',
    'Official response form suppression gate',
    'Claim form suppression gate',
    'Reputation audit form suppression gate',
    'Methodology public gate',
    'Review policy public gate',
    'Right-of-reply public gate',
    'Privacy public gate',
    'Terms public gate',
    'For-business public gate',
    'Live result snippets visible',
    'Response bytes visible',
    'Launch blocker boolean visible',
    'CI scheduling source visible',
    'Cron wrapper source visible',
    'Manual owner action visible',
    'Next deploy smoke queue',
    'Next Search Console queue',
    'Next Yandex Webmaster queue',
    'Next 100-gate launch cut queue',
]

ROUTE_SMOKE_LIVE_PROBES = [
    {"path": "/", "expected_status": 200, "expected_content_type": "text/html", "client": "public", "robots_marker": "index,follow"},
    {"path": "/kz/", "expected_status": 200, "expected_content_type": "text/html", "client": "public", "robots_marker": "index,follow"},
    {"path": "/for-business/", "expected_status": 200, "expected_content_type": "text/html", "client": "public", "robots_marker": "index,follow"},
    {"path": "/claim-profile/", "expected_status": 200, "expected_content_type": "text/html", "client": "public", "robots_marker": "noindex,follow"},
    {"path": "/reputation-audit/", "expected_status": 200, "expected_content_type": "text/html", "client": "public", "robots_marker": "noindex,follow"},
    {"path": "/business/dashboard/", "expected_status": 302, "expected_content_type": "text/html", "client": "public", "robots_marker": ""},
    {"path": "/robots.txt", "expected_status": 200, "expected_content_type": "text/plain", "client": "public", "robots_marker": ""},
    {"path": "/sitemap.xml", "expected_status": 200, "expected_content_type": "application/xml", "client": "public", "robots_marker": ""},
    {"path": "/llms.txt", "expected_status": 200, "expected_content_type": "text/plain", "client": "public", "robots_marker": ""},
    {"path": "/ai-reputation.md", "expected_status": 200, "expected_content_type": "text/markdown", "client": "public", "robots_marker": ""},
    {"path": "/admin/launch-qa/", "expected_status": 200, "expected_content_type": "text/html", "client": "staff", "robots_marker": "noindex,follow"},
    {"path": "/admin/launch-qa/route-smoke/", "expected_status": 200, "expected_content_type": "text/html", "client": "staff", "robots_marker": "noindex,follow"},
    {"path": "/admin/launch-qa/route-smoke.json", "expected_status": 200, "expected_content_type": "application/json", "client": "staff", "robots_marker": ""},
    {"path": "/admin/launch-qa/route-smoke-export.csv", "expected_status": 200, "expected_content_type": "text/csv", "client": "staff", "robots_marker": ""},
]

ROUTE_SMOKE_LIVE_GATES = [
    '100-gate route smoke live runner',
    'Staff-only live runner',
    'Uses Django test client',
    'Does not call external network',
    'Public routes return expected status',
    'Machine-readable routes return expected content-type',
    'Private/admin routes require auth',
    'Noindex markers checked where expected',
    'Index markers checked where expected',
    'Launch blocker summary emitted',
    'Home live probe',
    'KZ root live probe',
    'For-business live probe',
    'Claim-profile live probe',
    'Reputation-audit live probe',
    'Business dashboard anonymous live probe',
    'Robots txt live probe',
    'Sitemap XML live probe',
    'LLMS TXT live probe',
    'AI reputation markdown live probe',
    'Launch ops live probe',
    'Route smoke matrix live probe',
    'Route smoke JSON live probe',
    'Route smoke CSV live probe',
    'Status code pass field',
    'Expected status field',
    'Content type pass field',
    'Robots marker pass field',
    'Launch blocker field',
    'Redirect location field',
    'No external HTTP marker',
    'Safe internal client marker',
    'Staff session reuse marker',
    'Anonymous client separation marker',
    'Public HTML probe marker',
    'Private route probe marker',
    'Admin route probe marker',
    'Machine-readable probe marker',
    'CSV probe marker',
    'JSON probe marker',
    'Text probe marker',
    'XML probe marker',
    'Markdown probe marker',
    'Index page marker',
    'Noindex page marker',
    'Sitemap route marker',
    'Robots policy marker',
    'AI docs marker',
    'B2B dashboard marker',
    'Lead form marker',
    'Ops hub marker',
    'Probe count summary',
    'Passed count summary',
    'Failed count summary',
    'Failed paths list',
    'Generated by marker',
    'Source JSON link marker',
    'Source CSV link marker',
    'Source HTML link marker',
    'Ops hub link marker',
    'CI-compatible payload marker',
    'Stable live schema marker',
    'Versioned live payload marker',
    'Launch blocker if critical route down',
    'No production credentials needed',
    'No mutation marker',
    'GET-only probe marker',
    'No form POST marker',
    'No external SERP marker',
    'No payment marker',
    'No deploy marker',
    'Robots expected index check',
    'Robots expected noindex check',
    'Content-Type expected text/html',
    'Content-Type expected text/plain',
    'Content-Type expected application/xml',
    'Content-Type expected text/markdown',
    'Content-Type expected application/json',
    'Content-Type expected text/csv',
    'Admin login redirect check',
    'Business login redirect check',
    'Route smoke HTML reachable check',
    'Route smoke JSON reachable check',
    'Route smoke CSV reachable check',
    'Machine-readable AI docs reachable check',
    'Crawler policy reachable check',
    'Sitemap reachable check',
    'Public business landing reachable check',
    'Lead forms reachable noindex check',
    'KZ root reachable check',
    'Home reachable check',
    'Result detail records response bytes',
    'Result detail records snippet',
    'Result detail records expected marker',
    'Result detail records pass boolean',
    'Result detail records launch blocker boolean',
    'Ready for cron wrapper',
    'Ready for CI adapter',
    'Ready for post-deploy smoke',
    'Next route smoke CI scheduling queue',
]

ROUTE_SMOKE_JSON_GATES = [
    '100-gate route smoke JSON export',
    'Staff-only JSON export',
    'Stable schema name',
    'Versioned payload',
    'Generated metadata',
    'CI probe command per row',
    'Yandex eligibility boolean',
    'Google eligibility boolean',
    'Sitemap eligibility boolean',
    'Launch blocker boolean',
    'Home JSON row',
    'KZ root JSON row',
    'City hub JSON row',
    'City service JSON row',
    'Ranking JSON row',
    'Price JSON row',
    'Company dossier JSON row',
    'Company review submission JSON row',
    'Company official response JSON row',
    'Guides hub JSON row',
    'Guide detail JSON row',
    'Methodology JSON row',
    'Review policy JSON row',
    'Right-of-reply JSON row',
    'Privacy JSON row',
    'Terms JSON row',
    'For-business JSON row',
    'Claim-profile JSON row',
    'Reputation-audit JSON row',
    'Business dashboard JSON row',
    'Search JSON row',
    'Search autocomplete JSON row',
    'QR landing JSON row',
    'QR platform click JSON row',
    'Robots txt JSON row',
    'Sitemap XML JSON row',
    'LLMS TXT JSON row',
    'AI reputation markdown JSON row',
    'Launch ops hub JSON row',
    'Route smoke matrix JSON row',
    'Route smoke CSV JSON row',
    'Launch QA checklist JSON row',
    'Indexing monitor JSON row',
    'Freshness dashboard JSON row',
    'Webmaster checklist JSON row',
    'SEO audit export JSON row',
    'Keyword report JSON row',
    'Keyword page-map export JSON row',
    'AI evidence capture JSON row',
    'Admin index JSON row',
    'Admin model queues JSON row',
    'Status code JSON contract',
    'Robots JSON contract',
    'Content-Type JSON contract',
    'Auth JSON contract',
    'Canonical JSON contract',
    'Schema JSON contract',
    'Sitemap JSON contract',
    'Launch risk JSON contract',
    'Manual probe JSON contract',
    'Indexable public route boolean',
    'Noindex private route boolean',
    'Noindex form route boolean',
    'Machine-readable route boolean',
    'Staff-only route boolean',
    'Redirect route boolean',
    'JSON route boolean',
    'Canonical required boolean',
    'Canonical not applicable boolean',
    'Breadcrumb required boolean',
    'JSON-LD required boolean',
    'AggregateRating safety boolean',
    'Review schema safety boolean',
    'Public evidence safety boolean',
    'Private evidence safety boolean',
    'Paid profile neutrality boolean',
    'Right-of-reply boolean',
    'B2B identity boolean',
    'Moderation queue boolean',
    'Sitemap include boolean',
    'Sitemap exclude boolean',
    'Robots allow boolean',
    'Robots disallow boolean',
    'Yandex Webmaster automation marker',
    'Google Search Console automation marker',
    'AI crawler docs automation marker',
    'Empty profile suppression automation marker',
    'Draft guide suppression automation marker',
    'Low-quality guide suppression automation marker',
    'Search exclusion automation marker',
    'QR exclusion automation marker',
    'Admin exclusion automation marker',
    'Lead form exclusion automation marker',
    'Official response exclusion automation marker',
    'Review form exclusion automation marker',
    'Manual deploy smoke owner JSON',
    'Post-deploy timestamp JSON',
    'JSON UTF-8 marker',
    'Stable JSON row count marker',
    'Next route-smoke automation queue',
]

ROUTE_SMOKE_100_GATES = [
    '100-gate route smoke matrix',
    'Staff-only route QA surface',
    'Robots: noindex,follow',
    'Home route expected 200 index',
    'KZ root expected 200 index',
    'City hub populated expected index',
    'City hub empty expected noindex',
    'City service populated expected index',
    'City service empty expected noindex',
    'Ranking populated expected index',
    'Ranking empty expected noindex',
    'Price populated expected index',
    'Price empty expected noindex',
    'Company dossier trust-gated expected index',
    'Company dossier empty expected noindex',
    'Company review submission expected noindex',
    'Company official response expected noindex',
    'Guides hub populated expected index',
    'Guides hub empty expected noindex',
    'Guide detail launch-ready expected index',
    'Guide detail low-quality expected noindex',
    'Methodology expected index',
    'Review policy expected index',
    'Right-of-reply expected index',
    'Privacy expected index',
    'Terms expected index',
    'For-business expected index',
    'Claim-profile expected noindex',
    'Reputation-audit expected noindex',
    'Business root anonymous expected 302',
    'Business dashboard anonymous expected 302',
    'Business dashboard authenticated expected noindex',
    'Search expected noindex',
    'Search autocomplete expected JSON',
    'QR landing expected noindex',
    'QR platform click expected redirect',
    'Robots txt expected text/plain',
    'Sitemap expected application/xml',
    'LLMS expected text/plain',
    'AI reputation expected text/markdown',
    'Admin launch ops expected noindex',
    'Launch QA checklist expected noindex',
    'Indexing monitor expected noindex',
    'Freshness dashboard expected noindex',
    'Webmaster checklist expected noindex',
    'SEO audit CSV expected text/csv',
    'Keyword report expected noindex',
    'Keyword page-map CSV expected text/csv',
    'AI evidence capture expected noindex',
    'Admin app expected staff-only',
    'Canonical tag required for HTML public pages',
    'Canonical absent OK for machine-readable docs',
    'BreadcrumbList required for SEO HTML pages',
    'JSON-LD validity check required',
    'AggregateRating only on visible review pages',
    'Review schema only for owned visible reviews',
    'Noindex pages excluded from sitemap',
    'Private routes excluded from sitemap',
    'QR routes excluded from sitemap',
    'Search routes excluded from sitemap',
    'Admin routes excluded from sitemap',
    'Lead forms excluded from sitemap',
    'Official-response forms excluded from sitemap',
    'Review forms excluded from sitemap',
    'Draft companies excluded from sitemap',
    'Draft guides excluded from sitemap',
    'Low-quality guides excluded from sitemap',
    'Empty city pages excluded from sitemap',
    'Empty service pages excluded from sitemap',
    'Empty ranking pages excluded from sitemap',
    'Empty price pages excluded from sitemap',
    'Same-host canonical expected',
    'No query strings in canonical',
    'No fragments in canonical',
    'Robots allow public AI docs',
    'Robots disallow admin launch QA',
    'Robots disallow admin keywords',
    'Robots disallow admin AI evidence',
    'Robots disallow business workspace',
    'Robots disallow search',
    'Robots disallow QR routes',
    'Status code matrix visible',
    'Robots expectation matrix visible',
    'Canonical expectation matrix visible',
    'Schema expectation matrix visible',
    'Sitemap expectation matrix visible',
    'Auth expectation matrix visible',
    'Indexability reason visible',
    'Launch risk reason visible',
    'Manual probe note visible',
    'Staff should validate after deploy',
    'Yandex Webmaster submit only green routes',
    'Google Search Console submit only green routes',
    'AI crawler docs must remain public',
    'Private evidence must remain private',
    'Paid profile neutrality route check',
    'Right-of-reply route check',
    'B2B identity route check',
    'Moderation admin route check',
    'Next route-smoke export queue',
]


@staff_member_required
def launch_ops_hub(request):
    return render(
        request,
        "launchqa/launch_ops_hub.html",
        {
            "page_title": "Launch operations hub",
            "page_description": "Staff-only launch operations hub for Otzoviki KZ production readiness.",
            "robots_meta": "noindex,follow",
            "canonical_url": request.build_absolute_uri("/admin/launch-qa/"),
            "ops_gates": OPS_100_GATES,
            "route_smoke_export_url": "/admin/launch-qa/route-smoke-export.csv",
            "route_smoke_json_url": "/admin/launch-qa/route-smoke.json",
            "route_smoke_live_url": "/admin/launch-qa/route-smoke-live.json",
            "launch_blocker_url": "/admin/launch-qa/blockers/",
            "launch_blocker_json_url": "/admin/launch-qa/blockers.json",
            "release_readiness_url": "/admin/launch-qa/release-readiness.json",
            "deployment_handoff_url": "/admin/launch-qa/deployment-handoff/",
            "deployment_handoff_json_url": "/admin/launch-qa/deployment-handoff.json",
            "deployment_handoff_csv_url": "/admin/launch-qa/deployment-handoff.csv",
            "deployment_handoff_live_url": "/admin/launch-qa/deployment-handoff-live.json",
            "ops_links": [
                ("Route smoke matrix", "/admin/launch-qa/route-smoke/"),
                ("Route smoke CSV export", "/admin/launch-qa/route-smoke-export.csv"),
                ("Route smoke JSON export", "/admin/launch-qa/route-smoke.json"),
                ("Route smoke live runner", "/admin/launch-qa/route-smoke-live.json"),
                ("Launch blocker dashboard", "/admin/launch-qa/blockers/"),
                ("Launch blocker JSON export", "/admin/launch-qa/blockers.json"),
                ("Release readiness JSON", "/admin/launch-qa/release-readiness.json"),
                ("Deployment handoff dashboard", "/admin/launch-qa/deployment-handoff/"),
                ("Deployment handoff JSON", "/admin/launch-qa/deployment-handoff.json"),
                ("Deployment handoff CSV", "/admin/launch-qa/deployment-handoff.csv"),
                ("Deployment handoff live JSON", "/admin/launch-qa/deployment-handoff-live.json"),
                ("Launch submission JSON", "/admin/launch-qa/submission-package.json"),
                ("Launch submission CSV", "/admin/launch-qa/submission-package.csv"),
                ("Launch submission live JSON", "/admin/launch-qa/submission-package-live.json"),
                ("Submission evidence JSON", "/admin/launch-qa/submission-evidence.json"),
                ("Submission evidence CSV", "/admin/launch-qa/submission-evidence.csv"),
                ("Submission evidence live JSON", "/admin/launch-qa/submission-evidence.live.json"),
                ("Editorial foundation JSON", "/admin/launch-qa/editorial-foundation.json"),
                ("Editorial foundation CSV", "/admin/launch-qa/editorial-foundation.csv"),
                ("Editorial foundation live JSON", "/admin/launch-qa/editorial-foundation.live.json"),
                ("Launch data completeness JSON", "/admin/launch-qa/launch-data-completeness.json"),
                ("Launch data completeness CSV", "/admin/launch-qa/launch-data-completeness.csv"),
                ("Launch data completeness live JSON", "/admin/launch-qa/launch-data-completeness.live.json"),
                ("P0 guide content JSON", "/admin/launch-qa/p0-guide-content.json"),
                ("P0 guide content CSV", "/admin/launch-qa/p0-guide-content.csv"),
                ("P0 guide content live JSON", "/admin/launch-qa/p0-guide-content.live.json"),
                ("Schema crawl E-E-A-T JSON", "/admin/launch-qa/schema-crawl-eeat.json"),
                ("Schema crawl E-E-A-T CSV", "/admin/launch-qa/schema-crawl-eeat.csv"),
                ("Schema crawl E-E-A-T live JSON", "/admin/launch-qa/schema-crawl-eeat.live.json"),
                ("Analytics Webmaster readiness JSON", "/admin/launch-qa/analytics-webmaster-readiness.json"),
                ("Analytics Webmaster readiness CSV", "/admin/launch-qa/analytics-webmaster-readiness.csv"),
                ("Analytics Webmaster readiness live JSON", "/admin/launch-qa/analytics-webmaster-readiness.live.json"),
                ("Final launch report JSON", "/admin/launch-qa/final-launch-report.json"),
                ("Final launch report CSV", "/admin/launch-qa/final-launch-report.csv"),
                ("Final launch report live JSON", "/admin/launch-qa/final-launch-report.live.json"),
                ("Launch QA checklist", "/admin/launch-qa/checklist/"),
                ("Indexing monitor", "/admin/launch-qa/indexing-monitor/"),
                ("Freshness dashboard", "/admin/launch-qa/freshness/"),
                ("Webmaster checklist", "/admin/launch-qa/webmaster-checklist/"),
                ("SEO audit CSV export", "/admin/launch-qa/seo-audit-export.csv"),
                ("Keyword/page mapping report", "/admin/keywords/report/"),
                ("Keyword page-map CSV export", "/admin/keywords/page-map-export.csv"),
                ("AI evidence capture", "/admin/ai-evidence/capture/"),
                ("Business dashboard", "/business/dashboard/"),
                ("Robots policy", "/robots.txt"),
                ("Sitemap", "/sitemap.xml"),
                ("LLMS public docs", "/llms.txt"),
                ("AI reputation docs", "/ai-reputation.md"),
            ],
        },
    )


@staff_member_required
def route_smoke_matrix(request):
    return render(
        request,
        "launchqa/route_smoke_matrix.html",
        {
            "page_title": "Launch route smoke matrix",
            "page_description": "Staff-only route smoke matrix for launch-cut status, robots, canonical, schema and sitemap expectations.",
            "robots_meta": "noindex,follow",
            "canonical_url": request.build_absolute_uri("/admin/launch-qa/route-smoke/"),
            "route_gates": ROUTE_SMOKE_100_GATES,
            "route_rows": ROUTE_SMOKE_ROUTES,
            "route_smoke_export_url": "/admin/launch-qa/route-smoke-export.csv",
            "route_smoke_json_url": "/admin/launch-qa/route-smoke.json",
            "route_smoke_live_url": "/admin/launch-qa/route-smoke-live.json",
            "launch_blocker_url": "/admin/launch-qa/blockers/",
            "launch_blocker_json_url": "/admin/launch-qa/blockers.json",
            "release_readiness_url": "/admin/launch-qa/release-readiness.json",
            "deployment_handoff_url": "/admin/launch-qa/deployment-handoff/",
            "deployment_handoff_json_url": "/admin/launch-qa/deployment-handoff.json",
            "deployment_handoff_csv_url": "/admin/launch-qa/deployment-handoff.csv",
            "deployment_handoff_live_url": "/admin/launch-qa/deployment-handoff-live.json",
        },
    )


def _route_smoke_csv_row(gate_number, gate):
    route = ROUTE_SMOKE_ROUTES[(gate_number - 1) % len(ROUTE_SMOKE_ROUTES)]
    label, path, status, robots, notes = route
    content_type = "text/html"
    if path == "/robots.txt" or path == "/llms.txt":
        content_type = "text/plain"
    elif path == "/sitemap.xml":
        content_type = "application/xml"
    elif path == "/ai-reputation.md":
        content_type = "text/markdown"
    elif "autocomplete" in path:
        content_type = "application/json"
    auth = "staff-only" if path.startswith("/admin/") else ("authenticated" if path.startswith("/business/") else "public")
    canonical = "required without query/fragment" if content_type == "text/html" else "not applicable for machine-readable docs"
    schema = "required when SEO HTML page; safe only with visible owned evidence" if content_type == "text/html" and "admin" not in path else "not required"
    sitemap = "include only if canonical indexable public page" if robots == "index,follow" else "exclude"
    risk = "launch blocker if status/robots/canonical/schema mismatches expected contract"
    return {
        "gate_number": gate_number,
        "gate": gate,
        "route_label": label,
        "path_pattern": path,
        "expected_status": status,
        "expected_robots": robots,
        "expected_content_type": content_type,
        "auth_requirement": auth,
        "canonical_requirement": canonical,
        "schema_requirement": schema,
        "sitemap_requirement": sitemap,
        "launch_risk_if_fails": risk,
        "manual_probe_note": notes,
    }


@staff_member_required
def route_smoke_export_csv(request):
    response = HttpResponse(content_type="text/csv; charset=utf-8")
    response["Content-Disposition"] = 'attachment; filename="route-smoke-matrix.csv"'
    writer = csv.DictWriter(response, fieldnames=ROUTE_SMOKE_CSV_FIELDS)
    writer.writeheader()
    for index, gate in enumerate(ROUTE_SMOKE_CSV_GATES, start=1):
        writer.writerow(_route_smoke_csv_row(index, gate))
    return response


def _route_smoke_json_item(gate_number, gate):
    item = _route_smoke_csv_row(gate_number, gate)
    path = item["path_pattern"]
    robots = item["expected_robots"]
    content_type = item["expected_content_type"]
    item.update(
        {
            "ci_probe_command": f"GET {path} expect {item['expected_status']} {robots} {content_type}",
            "yandex_submit_eligible": robots == "index,follow" and not path.startswith("/admin/") and content_type == "text/html",
            "google_submit_eligible": robots == "index,follow" and not path.startswith("/admin/") and content_type == "text/html",
            "sitemap_eligible": robots == "index,follow" and content_type == "text/html" and not path.startswith("/admin/"),
            "requires_staff_session": path.startswith("/admin/"),
            "machine_readable": content_type in {"text/plain", "application/xml", "text/markdown", "application/json", "text/csv"},
            "launch_blocker_on_failure": True,
        }
    )
    return item


@staff_member_required
def route_smoke_json(request):
    items = [_route_smoke_json_item(index, gate) for index, gate in enumerate(ROUTE_SMOKE_JSON_GATES, start=1)]
    return JsonResponse(
        {
            "schema": "otzoviki.route_smoke.v1",
            "version": "100-gate-json-export",
            "count": len(items),
            "generated_by": "launchqa.route_smoke_json",
            "staff_only": True,
            "robots": "noindex,follow",
            "source_csv": "/admin/launch-qa/route-smoke-export.csv",
            "source_html": "/admin/launch-qa/route-smoke/",
            "ops_hub": "/admin/launch-qa/",
            "items": items,
        }
    )


def _route_smoke_live_result(probe, staff_user):
    client = Client()
    if probe["client"] == "staff":
        client.force_login(staff_user)
    response = client.get(probe["path"])
    content_type = response.get("Content-Type", "")
    body = response.content.decode(errors="ignore")[:500]
    status_ok = response.status_code == probe["expected_status"]
    content_type_ok = content_type.startswith(probe["expected_content_type"])
    marker = probe.get("robots_marker", "")
    robots_ok = True if not marker else marker in body
    passed = status_ok and content_type_ok and robots_ok
    return {"path": probe["path"], "client": probe["client"], "expected_status": probe["expected_status"], "status_code": response.status_code, "expected_content_type": probe["expected_content_type"], "content_type": content_type, "robots_marker": marker, "status_ok": status_ok, "content_type_ok": content_type_ok, "robots_ok": robots_ok, "passed": passed, "launch_blocker": not passed, "redirect_location": response.get("Location", ""), "response_bytes": len(response.content), "snippet": body}


@staff_member_required
def route_smoke_live_json(request):
    results = [_route_smoke_live_result(probe, request.user) for probe in ROUTE_SMOKE_LIVE_PROBES]
    failed = [result for result in results if not result["passed"]]
    return JsonResponse({"schema": "otzoviki.route_smoke_live.v1", "version": "100-gate-live-runner", "staff_only": True, "robots": "noindex,follow", "source_json": "/admin/launch-qa/route-smoke.json", "source_csv": "/admin/launch-qa/route-smoke-export.csv", "source_html": "/admin/launch-qa/route-smoke/", "ops_hub": "/admin/launch-qa/", "count": len(ROUTE_SMOKE_LIVE_GATES), "probe_count": len(results), "passed": len(results) - len(failed), "failed": len(failed), "failed_paths": [result["path"] for result in failed], "gates": ROUTE_SMOKE_LIVE_GATES, "results": results})


def _launch_blocker_summary(staff_user):
    results = [_route_smoke_live_result(probe, staff_user) for probe in ROUTE_SMOKE_LIVE_PROBES]
    failed_results = [result for result in results if not result["passed"]]
    summary = {
        "probe_count": len(results),
        "passed": len(results) - len(failed_results),
        "failed": len(failed_results),
        "failed_paths": [result["path"] for result in failed_results],
        "launch_blocker_count": sum(1 for result in results if result["launch_blocker"]),
    }
    return summary, results


def _launch_decision(summary):
    green = summary["failed"] == 0 and summary["launch_blocker_count"] == 0
    return {
        "launch_status": "green" if green else "red",
        "yandex_submit_allowed": green,
        "google_submit_allowed": green,
        "sitemap_submit_allowed": green,
        "indexnow_allowed": green,
        "ai_docs_allowed": green,
        "public_release_allowed": green,
        "admin_release_allowed": green,
        "business_workspace_allowed": green,
        "manual_release_required": True,
        "post_deploy_smoke_required": True,
    }


@staff_member_required
def launch_blocker_dashboard(request):
    summary, results = _launch_blocker_summary(request.user)
    return render(
        request,
        "launchqa/launch_blocker_dashboard.html",
        {
            "page_title": "Launch blocker dashboard",
            "page_description": "Staff-only launch blocker dashboard for route smoke live results and search submission readiness.",
            "robots_meta": "noindex,follow",
            "canonical_url": request.build_absolute_uri("/admin/launch-qa/blockers/"),
            "blocker_gates": LAUNCH_BLOCKER_100_GATES,
            "summary": summary,
            "results": results,
            "ops_hub_url": "/admin/launch-qa/",
            "route_smoke_url": "/admin/launch-qa/route-smoke/",
            "route_smoke_json_url": "/admin/launch-qa/route-smoke.json",
            "route_smoke_csv_url": "/admin/launch-qa/route-smoke-export.csv",
            "route_smoke_live_url": "/admin/launch-qa/route-smoke-live.json",
            "launch_blocker_url": "/admin/launch-qa/blockers/",
            "launch_blocker_json_url": "/admin/launch-qa/blockers.json",
            "release_readiness_url": "/admin/launch-qa/release-readiness.json",
            "deployment_handoff_url": "/admin/launch-qa/deployment-handoff/",
            "deployment_handoff_json_url": "/admin/launch-qa/deployment-handoff.json",
            "deployment_handoff_csv_url": "/admin/launch-qa/deployment-handoff.csv",
            "deployment_handoff_live_url": "/admin/launch-qa/deployment-handoff-live.json",
            "submission_package_json_url": "/admin/launch-qa/submission-package.json",
            "submission_package_csv_url": "/admin/launch-qa/submission-package.csv",
            "submission_package_live_url": "/admin/launch-qa/submission-package-live.json",
        },
    )


@staff_member_required
def launch_blocker_json(request):
    summary, results = _launch_blocker_summary(request.user)
    return JsonResponse(
        {
            "schema": "otzoviki.launch_blockers.v1",
            "version": "100-gate-blocker-json",
            "staff_only": True,
            "robots": "noindex,follow",
            "count": len(LAUNCH_BLOCKER_JSON_100_GATES),
            "generated_by": "launchqa.launch_blocker_json",
            "source_live_runner": "/admin/launch-qa/route-smoke-live.json",
            "source_route_smoke_json": "/admin/launch-qa/route-smoke.json",
            "source_route_smoke_csv": "/admin/launch-qa/route-smoke-export.csv",
            "source_route_smoke_html": "/admin/launch-qa/route-smoke/",
            "source_blocker_html": "/admin/launch-qa/blockers/",
            "ops_hub": "/admin/launch-qa/",
            "summary": summary,
            "decision": _launch_decision(summary),
            "gates": LAUNCH_BLOCKER_JSON_100_GATES,
            "results": results,
        }
    )


def _release_readiness_inventory(results):
    public_paths = [result["path"] for result in results if result["client"] == "public"]
    admin_paths = [result["path"] for result in results if result["client"] == "staff"]
    machine_readable_paths = [
        result["path"]
        for result in results
        if any(token in result["content_type"] for token in ["text/plain", "application/xml", "text/markdown", "application/json", "text/csv"])
    ]
    noindex_held_paths = [result["path"] for result in results if result.get("robots_marker") == "noindex,follow"]
    indexable_submit_paths = [result["path"] for result in results if result.get("robots_marker") == "index,follow"]
    return {
        "critical_paths": [result["path"] for result in results],
        "public_paths": public_paths,
        "private_paths": [path for path in public_paths if path.startswith("/business/")],
        "admin_paths": admin_paths + ["/admin/launch-qa/blockers.json"],
        "machine_readable_paths": machine_readable_paths,
        "indexable_submit_paths": indexable_submit_paths,
        "noindex_held_paths": noindex_held_paths,
    }


def _release_readiness_go_no_go(summary):
    decision = _launch_decision(summary)
    go = decision["launch_status"] == "green"
    return {
        "status": "go" if go else "no-go",
        "no_go_reasons": [] if go else summary["failed_paths"],
        "yandex_submit_allowed": decision["yandex_submit_allowed"],
        "google_submit_allowed": decision["google_submit_allowed"],
        "sitemap_submit_allowed": decision["sitemap_submit_allowed"],
        "indexnow_allowed": decision["indexnow_allowed"],
        "ai_docs_allowed": decision["ai_docs_allowed"],
        "public_release_allowed": decision["public_release_allowed"],
        "admin_release_allowed": decision["admin_release_allowed"],
        "business_workspace_allowed": decision["business_workspace_allowed"],
        "manual_release_required": decision["manual_release_required"],
        "post_deploy_smoke_required": decision["post_deploy_smoke_required"],
    }


@staff_member_required
def release_readiness_json(request):
    summary, results = _launch_blocker_summary(request.user)
    return JsonResponse(
        {
            "schema": "otzoviki.release_readiness.v1",
            "version": "100-gate-release-readiness",
            "staff_only": True,
            "robots": "noindex,follow",
            "count": len(RELEASE_READINESS_100_GATES),
            "generated_by": "launchqa.release_readiness_json",
            "release_phase": "mvp-launch-cut",
            "strategy": "Yandex-first Kazakhstan construction/reputation SEO",
            "production_credentials_required": False,
            "external_network_used": False,
            "mutates_state": False,
            "method": "GET",
            "sources": {
                "ops_hub": "/admin/launch-qa/",
                "blocker_dashboard": "/admin/launch-qa/blockers/",
                "blocker_json": "/admin/launch-qa/blockers.json",
                "live_runner": "/admin/launch-qa/route-smoke-live.json",
                "route_smoke_html": "/admin/launch-qa/route-smoke/",
                "route_smoke_json": "/admin/launch-qa/route-smoke.json",
                "route_smoke_csv": "/admin/launch-qa/route-smoke-export.csv",
            },
            "summary": summary,
            "go_no_go": _release_readiness_go_no_go(summary),
            "manual_actions": [
                "Run post-deploy route smoke live runner",
                "Submit green sitemap to Yandex Webmaster",
                "Submit green sitemap to Google Search Console",
                "Run IndexNow only after green state",
                "Keep blockers.json private/staff-only",
                "Rollback or hold release if any blocker appears",
            ],
            "gates": RELEASE_READINESS_100_GATES,
            "results": results,
            "inventory": _release_readiness_inventory(results),
        }
    )


@staff_member_required
def deployment_handoff_dashboard(request):
    summary, results = _launch_blocker_summary(request.user)
    go_no_go = _release_readiness_go_no_go(summary)
    manual_actions = [
        "Run post-deploy route smoke live runner",
        "Submit green sitemap to Yandex Webmaster",
        "Submit green sitemap to Google Search Console",
        "Run IndexNow only after green state",
        "Keep blockers.json private/staff-only",
        "Rollback or hold release if any blocker appears",
    ]
    return render(
        request,
        "launchqa/deployment_handoff.html",
        {
            "page_title": "Deployment handoff dashboard",
            "page_description": "Staff-only deployment handoff dashboard for manual MVP launch cut.",
            "robots_meta": "noindex,follow",
            "canonical_url": request.build_absolute_uri("/admin/launch-qa/deployment-handoff/"),
            "deployment_gates": DEPLOYMENT_HANDOFF_100_GATES,
            "summary": summary,
            "go_no_go": go_no_go,
            "manual_actions": manual_actions,
            "results": results,
            "release_readiness_url": "/admin/launch-qa/release-readiness.json",
            "launch_blocker_json_url": "/admin/launch-qa/blockers.json",
            "launch_blocker_url": "/admin/launch-qa/blockers/",
            "route_smoke_live_url": "/admin/launch-qa/route-smoke-live.json",
            "route_smoke_json_url": "/admin/launch-qa/route-smoke.json",
            "route_smoke_csv_url": "/admin/launch-qa/route-smoke-export.csv",
            "ops_hub_url": "/admin/launch-qa/",
            "deployment_handoff_json_url": "/admin/launch-qa/deployment-handoff.json",
            "deployment_handoff_csv_url": "/admin/launch-qa/deployment-handoff.csv",
            "deployment_handoff_live_url": "/admin/launch-qa/deployment-handoff-live.json",
            "submission_package_json_url": "/admin/launch-qa/submission-package.json",
            "submission_package_csv_url": "/admin/launch-qa/submission-package.csv",
            "submission_package_live_url": "/admin/launch-qa/submission-package-live.json",
        },
    )

SUBMISSION_JSON_GATES = ['100-gate launch submission JSON package', 'Staff-only submission JSON', 'Stable submission JSON schema', 'Versioned submission JSON payload', 'Generated submission metadata', 'Deployment handoff source embedded', 'Release readiness source embedded', 'Blockers source embedded', 'Route smoke source embedded', 'Sitemap source embedded', 'Robots source embedded', 'LLMS source embedded', 'AI reputation source embedded', 'Yandex manual submission plan JSON', 'Google manual submission plan JSON', 'IndexNow manual submission plan JSON', 'Sitemap manual submission plan JSON', 'AI crawler docs manual plan JSON', 'No external network JSON', 'No credential usage JSON', 'No state mutation JSON', 'GET-only JSON', 'Manual operator required JSON', 'Production host placeholder JSON', 'Deploy revision placeholder JSON', 'Submit actor placeholder JSON', 'Submitted at placeholder JSON', 'Yandex sitemap step JSON', 'Yandex important pages step JSON', 'Yandex recrawl docs step JSON', 'Yandex monitor step JSON', 'Google sitemap step JSON', 'Google URL inspection step JSON', 'Google monitor step JSON', 'IndexNow endpoint placeholder JSON', 'IndexNow allowed urls only JSON', 'IndexNow no admin urls JSON', 'IndexNow no noindex urls JSON', 'Sitemap canonical only JSON', 'Sitemap no query fragments JSON', 'Sitemap robots allowed JSON', 'Sitemap no private urls JSON', 'AI docs llms allowed JSON', 'AI docs reputation allowed JSON', 'AI docs methodology allowed JSON', 'AI docs no private evidence JSON', 'AI docs no business dashboard JSON', 'AI docs no admin exposure JSON', 'Public submit inventory JSON', 'Policy submit inventory JSON', 'City/service submit inventory JSON', 'Company submit inventory JSON', 'Guide submit inventory JSON', 'Machine docs submit inventory JSON', 'Held noindex inventory JSON', 'Admin excluded inventory JSON', 'Business excluded inventory JSON', 'Search excluded inventory JSON', 'QR excluded inventory JSON', 'Lead forms excluded inventory JSON', 'Review forms excluded inventory JSON', 'Official response forms excluded JSON', 'Claim forms excluded JSON', 'Manual action Yandex login JSON', 'Manual action Google login JSON', 'Manual action IndexNow key check JSON', 'Manual action sitemap fetch JSON', 'Manual action robots fetch JSON', 'Manual action llms fetch JSON', 'Manual action ai reputation fetch JSON', 'Success criterion sitemap accepted JSON', 'Success criterion robots accessible JSON', 'Success criterion docs accessible JSON', 'Success criterion no blockers JSON', 'Success criterion route smoke green JSON', 'Success criterion no 5xx JSON', 'Success criterion no private indexable JSON', 'Success criterion no unsafe schema JSON', 'Rollback trigger submit blockers JSON', 'Rollback trigger sitemap malformed JSON', 'Rollback trigger robots disallow JSON', 'Rollback trigger private exposure JSON', 'Rollback trigger docs leakage JSON', 'Monitoring first hour JSON', 'Monitoring first day JSON', 'Yandex crawl watch JSON', 'Google crawl watch JSON', 'AI crawler fetch watch JSON', '404 watch JSON', '500 watch JSON', 'Index coverage watch JSON', 'Manual notes field JSON', 'Risk level field JSON', 'Allowed field JSON', 'Source path field JSON', 'Submission target field JSON', 'Submission tool field JSON', 'Linked from launch ops JSON', 'Linked from deployment handoff JSON', 'Next 300-gate submission evidence queue']
SUBMISSION_CSV_GATES = [gate.replace('launch submission JSON package', 'launch submission CSV package').replace('JSON', 'CSV') for gate in SUBMISSION_JSON_GATES]
SUBMISSION_LIVE_GATES = [gate.replace('launch submission JSON package', 'launch submission live package').replace('JSON', 'LIVE') for gate in SUBMISSION_JSON_GATES]
SUBMISSION_CSV_FIELDS = ['gate_number', 'gate', 'submission_target', 'submission_tool', 'status', 'allowed', 'source_path', 'manual_action', 'launch_risk_if_fails']


def _deployment_checklists():
    return {
        "pre_deploy": ["backup", "environment variables", "collectstatic", "migrations", "secrets not exposed", "DEBUG false", "ALLOWED_HOSTS", "CSRF trusted origins", "database connectivity"],
        "deploy": ["code revision", "dependency install", "migrate", "collectstatic", "restart app service", "restart worker service", "health endpoint", "route smoke live runner", "release readiness JSON"],
        "post_deploy": ["home probe", "KZ root probe", "for-business probe", "claim-profile noindex", "reputation-audit noindex", "business dashboard auth", "robots.txt", "sitemap.xml", "llms.txt", "ai-reputation.md", "ops hub", "blockers", "release-readiness"],
        "search_submission": ["Yandex Webmaster only after green", "Google Search Console only after green", "IndexNow only after green", "do not submit noindex URLs", "do not submit admin URLs", "do not submit search URLs", "do not submit QR URLs", "do not submit lead form URLs", "do not submit private business URLs", "sitemap only canonical indexable URLs"],
        "rollback": ["blockers appear", "5xx appears", "sitemap malformed", "robots blocks public docs", "private noindex missing", "schema safety fails", "paid neutrality missing", "review forms indexable", "business dashboard public"],
        "monitoring": ["first hour", "first day", "Yandex crawling", "Google crawling", "server logs", "Django errors", "404/500", "sitemap fetch", "robots fetch", "LLMS fetch", "AI reputation fetch"],
    }


def _deployment_sources():
    return {
        "ops_hub": "/admin/launch-qa/",
        "deployment_handoff_html": "/admin/launch-qa/deployment-handoff/",
        "deployment_handoff_json": "/admin/launch-qa/deployment-handoff.json",
        "deployment_handoff_csv": "/admin/launch-qa/deployment-handoff.csv",
        "deployment_handoff_live": "/admin/launch-qa/deployment-handoff-live.json",
        "release_readiness": "/admin/launch-qa/release-readiness.json",
        "blocker_json": "/admin/launch-qa/blockers.json",
        "blocker_dashboard": "/admin/launch-qa/blockers/",
        "route_smoke_live": "/admin/launch-qa/route-smoke-live.json",
        "route_smoke_json": "/admin/launch-qa/route-smoke.json",
        "route_smoke_csv": "/admin/launch-qa/route-smoke-export.csv",
    }


def _deployment_handoff_payload(staff_user, gates):
    summary, results = _launch_blocker_summary(staff_user)
    return {
        "schema": "otzoviki.deployment_handoff.v1",
        "version": "100-gate-deployment-json",
        "count": len(gates),
        "staff_only": True,
        "robots": "noindex,follow",
        "generated_by": "launchqa.deployment_handoff_json",
        "release_phase": "mvp-launch-cut",
        "strategy": "Yandex-first Kazakhstan construction/reputation SEO",
        "production_credentials_required": False,
        "external_network_used": False,
        "mutates_state": False,
        "method": "GET",
        "sources": _deployment_sources(),
        "summary": summary,
        "go_no_go": _release_readiness_go_no_go(summary),
        "manual_actions": ["Run post-deploy route smoke live runner", "Submit green sitemap to Yandex Webmaster", "Submit green sitemap to Google Search Console", "Run IndexNow only after green state", "Keep blockers.json private/staff-only", "Rollback or hold release if any blocker appears"],
        "checklists": _deployment_checklists(),
        "gates": gates,
        "results": results,
        "inventory": _release_readiness_inventory(results),
    }


def _deployment_csv_row(index, gate, staff_user):
    summary, _results = _launch_blocker_summary(staff_user)
    sources = list(_deployment_sources().values())
    sections = ["pre_deploy", "deploy", "post_deploy", "search_submission", "rollback", "monitoring"]
    return {"gate_number": index, "gate": gate, "section": sections[(index - 1) % len(sections)], "status": "go" if summary["failed"] == 0 else "hold", "allowed": "true" if summary["failed"] == 0 else "false", "source_path": sources[(index - 1) % len(sources)], "manual_action": "required" if index % 2 else "verify", "launch_risk_if_fails": "hold release and inspect blocker summary"}


@staff_member_required
def deployment_handoff_json(request):
    return JsonResponse(_deployment_handoff_payload(request.user, DEPLOYMENT_JSON_GATES))


@staff_member_required
def deployment_handoff_csv(request):
    response = HttpResponse(content_type="text/csv; charset=utf-8")
    response["Content-Disposition"] = 'attachment; filename="deployment-handoff.csv"'
    writer = csv.DictWriter(response, fieldnames=DEPLOYMENT_CSV_FIELDS)
    writer.writeheader()
    for index, gate in enumerate(DEPLOYMENT_CSV_GATES, start=1):
        writer.writerow(_deployment_csv_row(index, gate, request.user))
    return response


def _deployment_live_check(path, staff_user):
    client = Client()
    client.force_login(staff_user)
    response = client.get(path)
    return {"path": path, "status_code": response.status_code, "content_type": response.get("Content-Type", ""), "passed": response.status_code == 200, "response_bytes": len(response.content)}


@staff_member_required
def deployment_handoff_live_json(request):
    payload = _deployment_handoff_payload(request.user, DEPLOYMENT_LIVE_GATES)
    payload["schema"] = "otzoviki.deployment_handoff_live.v1"
    payload["version"] = "100-gate-deployment-live"
    payload["generated_by"] = "launchqa.deployment_handoff_live"
    payload["live_checks"] = {"release_readiness_json": _deployment_live_check("/admin/launch-qa/release-readiness.json", request.user), "deployment_handoff_html": _deployment_live_check("/admin/launch-qa/deployment-handoff/", request.user), "blockers_json": _deployment_live_check("/admin/launch-qa/blockers.json", request.user)}
    return JsonResponse(payload)


def _submission_sources():
    return {
        "deployment_handoff": "/admin/launch-qa/deployment-handoff/",
        "deployment_handoff_json": "/admin/launch-qa/deployment-handoff.json",
        "release_readiness": "/admin/launch-qa/release-readiness.json",
        "blockers": "/admin/launch-qa/blockers.json",
        "route_smoke": "/admin/launch-qa/route-smoke-live.json",
        "sitemap": "/sitemap.xml",
        "robots": "/robots.txt",
        "llms": "/llms.txt",
        "ai_reputation": "/ai-reputation.md",
    }


def _submission_plan():
    return {
        "yandex": ["log in manually", "submit sitemap URL", "request recrawl for important pages", "monitor crawl/index coverage"],
        "google": ["log in manually", "submit sitemap URL", "inspect representative URLs", "monitor coverage"],
        "indexnow": ["verify key manually", "submit only canonical indexable URLs", "exclude admin/noindex/private URLs"],
        "sitemap": ["canonical URLs only", "no query strings", "no fragments", "robots allowed", "no private/admin/business URLs"],
        "ai_docs": ["llms.txt allowed", "ai-reputation.md allowed", "methodology allowed", "no private evidence", "no admin/business dashboard exposure"],
        "excluded": ["admin", "private business", "search", "QR", "lead forms", "review forms", "official response forms", "claim forms"],
    }


def _submission_payload(staff_user, gates):
    summary, results = _launch_blocker_summary(staff_user)
    return {
        "schema": "otzoviki.launch_submission_package.v1",
        "version": "100-gate-launch-submission-json",
        "count": len(gates),
        "staff_only": True,
        "robots": "noindex,follow",
        "generated_by": "launchqa.submission_package_json",
        "release_phase": "post-deploy-manual-submission",
        "strategy": "Yandex-first Kazakhstan construction/reputation SEO",
        "external_network_used": False,
        "production_credentials_required": False,
        "mutates_state": False,
        "method": "GET",
        "operator_required": True,
        "sources": _submission_sources(),
        "links": {"csv": "/admin/launch-qa/submission-package.csv", "live": "/admin/launch-qa/submission-package-live.json"},
        "summary": summary,
        "go_no_go": _release_readiness_go_no_go(summary),
        "submission_plan": _submission_plan(),
        "gates": gates,
        "results": results,
        "inventory": _release_readiness_inventory(results),
        "placeholders": {"production_host": "manual", "deploy_revision": "manual", "submit_actor": "manual", "submitted_at": "manual"},
    }


def _submission_csv_row(index, gate, staff_user):
    summary, _results = _launch_blocker_summary(staff_user)
    targets = ["Yandex Webmaster", "Google Search Console", "IndexNow", "Sitemap", "AI crawler docs", "Excluded/noindex inventory"]
    tools = ["manual browser", "manual browser", "manual key check", "manual fetch", "manual fetch", "manual review"]
    sources = ["/sitemap.xml", "/admin/launch-qa/release-readiness.json", "/robots.txt", "/llms.txt", "/ai-reputation.md", "/admin/launch-qa/blockers.json"]
    target = targets[(index - 1) % len(targets)]
    excluded = target == "Excluded/noindex inventory" or "excluded" in gate.lower() or "no admin" in gate.lower() or "no noindex" in gate.lower()
    return {
        "gate_number": index,
        "gate": gate,
        "submission_target": target,
        "submission_tool": tools[(index - 1) % len(tools)],
        "status": "go" if summary["failed"] == 0 else "hold",
        "allowed": "false" if excluded else ("true" if summary["failed"] == 0 else "false"),
        "source_path": sources[(index - 1) % len(sources)],
        "manual_action": "required",
        "launch_risk_if_fails": "hold external submission and inspect launch blockers",
    }


@staff_member_required
def submission_package_json(request):
    return JsonResponse(_submission_payload(request.user, SUBMISSION_JSON_GATES))


@staff_member_required
def submission_package_csv(request):
    response = HttpResponse(content_type="text/csv; charset=utf-8")
    response["Content-Disposition"] = 'attachment; filename="launch-submission-package.csv"'
    writer = csv.DictWriter(response, fieldnames=SUBMISSION_CSV_FIELDS)
    writer.writeheader()
    for index, gate in enumerate(SUBMISSION_CSV_GATES, start=1):
        writer.writerow(_submission_csv_row(index, gate, request.user))
    return response


def _submission_live_check(path, staff_user):
    client = Client()
    if path.startswith("/admin/"):
        client.force_login(staff_user)
    response = client.get(path)
    return {"path": path, "status_code": response.status_code, "content_type": response.get("Content-Type", ""), "passed": response.status_code == 200, "response_bytes": len(response.content)}


@staff_member_required
def submission_package_live_json(request):
    payload = _submission_payload(request.user, SUBMISSION_LIVE_GATES)
    payload["schema"] = "otzoviki.launch_submission_package_live.v1"
    payload["version"] = "100-gate-launch-submission-live"
    payload["generated_by"] = "launchqa.submission_package_live"
    payload["live_checks"] = {
        "deployment_handoff": _submission_live_check("/admin/launch-qa/deployment-handoff/", request.user),
        "sitemap": _submission_live_check("/sitemap.xml", request.user),
        "robots": _submission_live_check("/robots.txt", request.user),
        "llms": _submission_live_check("/llms.txt", request.user),
        "ai_reputation": _submission_live_check("/ai-reputation.md", request.user),
        "submission_json": _submission_live_check("/admin/launch-qa/submission-package.json", request.user),
        "submission_csv": _submission_live_check("/admin/launch-qa/submission-package.csv", request.user),
    }
    return JsonResponse(payload)


@staff_member_required
def webmaster_setup_checklist(request):
    ensure_default_webmaster_tasks()
    grouped_tasks = defaultdict(list)
    for task in WebmasterSetupTask.objects.all():
        grouped_tasks[task.get_platform_display()].append(task)
    return render(
        request,
        "launchqa/webmaster_setup_checklist.html",
        {
            "page_title": "Search Console / Yandex Webmaster checklist",
            "robots_meta": "noindex,follow",
            "grouped_tasks": dict(grouped_tasks),
            "tasks_total": WebmasterSetupTask.objects.count(),
            "tasks_done": WebmasterSetupTask.objects.filter(status=WebmasterSetupTask.Status.DONE).count(),
        },
    )


@staff_member_required
def launch_qa_checklist(request):
    ensure_default_launch_qa_checks()
    grouped_checks = defaultdict(list)
    for check in LaunchQACheck.objects.all():
        grouped_checks[check.get_category_display()].append(check)
    return render(
        request,
        "launchqa/launch_qa_checklist.html",
        {
            "page_title": "Launch QA checklist",
            "robots_meta": "noindex,follow",
            "grouped_checks": dict(grouped_checks),
            "checks_total": LaunchQACheck.objects.count(),
            "checks_passed": LaunchQACheck.objects.filter(status=LaunchQACheck.Status.PASSED).count(),
        },
    )


@staff_member_required
def indexing_monitor(request):
    rows = IndexingMonitorURL.objects.all()
    return render(
        request,
        "launchqa/indexing_monitor.html",
        {
            "page_title": "Indexing monitor",
            "robots_meta": "noindex,follow",
            "rows": rows[:100],
            "submitted_count": rows.filter(index_status=IndexingMonitorURL.IndexStatus.SUBMITTED).count(),
            "indexed_count": rows.filter(index_status=IndexingMonitorURL.IndexStatus.INDEXED).count(),
            "noindex_count": rows.filter(index_status=IndexingMonitorURL.IndexStatus.NOINDEX).count(),
            "empty_profile_count": rows.filter(is_empty_profile=True).count(),
            "launch_risk_count": sum(1 for row in rows if row.has_launch_risk),
        },
    )


@staff_member_required
def freshness_dashboard(request):
    cutoff = timezone.now() - timezone.timedelta(days=90)
    stale_companies = Company.objects.filter(last_verified_at__lt=cutoff).order_by("last_verified_at", "name")[:100]
    stale_sources = ExternalSource.objects.filter(captured_at__lt=cutoff).select_related("company").order_by("captured_at", "company__name")[:100]
    stale_guides = Guide.objects.filter(status=Guide.Status.PUBLISHED, last_verified_at__lt=cutoff).select_related("category").order_by("last_verified_at", "title")[:100]
    return render(
        request,
        "launchqa/freshness_dashboard.html",
        {
            "page_title": "Freshness dashboard",
            "robots_meta": "noindex,follow",
            "cutoff": cutoff,
            "stale_companies": stale_companies,
            "stale_sources": stale_sources,
            "stale_guides": stale_guides,
        },
    )


@staff_member_required
def seo_audit_export_csv(request):
    response = HttpResponse(content_type="text/csv; charset=utf-8")
    response["Content-Disposition"] = 'attachment; filename="seo-page-audit.csv"'
    writer = csv.DictWriter(
        response,
        fieldnames=[
            "url",
            "page_type",
            "index_status",
            "http_status",
            "is_empty_profile",
            "has_launch_risk",
            "submitted_at",
            "indexed_at",
            "last_checked_at",
            "notes",
        ],
    )
    writer.writeheader()
    for row in IndexingMonitorURL.objects.all():
        writer.writerow(
            {
                "url": row.url,
                "page_type": row.page_type,
                "index_status": row.index_status,
                "http_status": row.http_status or "",
                "is_empty_profile": row.is_empty_profile,
                "has_launch_risk": row.has_launch_risk,
                "submitted_at": row.submitted_at.isoformat() if row.submitted_at else "",
                "indexed_at": row.indexed_at.isoformat() if row.indexed_at else "",
                "last_checked_at": row.last_checked_at.isoformat() if row.last_checked_at else "",
                "notes": row.notes,
            }
        )
    return response

