# Generated by Django 5.2.15 on 2026-06-11 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('yandex', 'Яндекс'), ('2gis', '2ГИС'), ('google', 'Google'), ('website', 'Сайт'), ('other', 'Другое')], max_length=24)),
                ('name', models.CharField(max_length=160)),
                ('url', models.URLField()),
                ('same_as_verified', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_sources', to='companies.company')),
            ],
            options={
                'ordering': ['company__name', 'source_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('owned_review', 'Otzoviki review'), ('external_footprint', 'External footprint'), ('complaint_signal', 'Complaint signal'), ('editorial_note', 'Editorial note'), ('private_proof', 'Private proof')], max_length=32)),
                ('title', models.CharField(max_length=220)),
                ('claim', models.TextField()),
                ('source_url', models.URLField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('admin_only', 'Admin only')], default='private', max_length=16)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='companies.company')),
                ('external_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_items', to='evidence.externalsource')),
            ],
            options={
                'verbose_name_plural': 'evidence',
                'ordering': ['-captured_at', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='externalsource',
            constraint=models.UniqueConstraint(fields=('company', 'source_type', 'url'), name='unique_company_external_source'),
        ),
    ]
