# Generated by Django 5.2.15 on 2026-06-11 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        ('reviews', '0003_alter_review_status_reviewmoderationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='private_evidence_items', to='reviews.review'),
        ),
    ]
