# Generated by Django 5.2.15 on 2026-06-11 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputationauditlead',
            name='ai_visibility_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reputationauditlead',
            name='audit_recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reputationauditlead',
            name='yandex_visibility_summary',
            field=models.TextField(blank=True),
        ),
    ]
