# Generated by Django 5.2.15 on 2026-06-11 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_reputationauditlead_ai_visibility_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialResponseModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('updated', 'Updated')], max_length=24)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_response_moderation_logs', to=settings.AUTH_USER_MODEL)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='business.officialresponse')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
