# Generated by Django 5.2.15 on 2026-06-11 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_claimprofilemoderationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputationauditlead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=16),
        ),
        migrations.CreateModel(
            name='ReputationAuditLeadStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('contacted', 'Contacted'), ('completed', 'Completed'), ('closed', 'Closed'), ('updated', 'Updated')], max_length=24)),
                ('from_status', models.CharField(blank=True, max_length=16)),
                ('to_status', models.CharField(blank=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='business.reputationauditlead')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_audit_status_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
