# Generated by Django 5.2.15 on 2026-06-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('role', models.CharField(choices=[('author', 'автор'), ('editor', 'редактор'), ('reviewer', 'эксперт-рецензент')], default='author', max_length=24)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('expertise', models.TextField(blank=True)),
                ('same_as_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='EditorialPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('methodology', 'Методология'), ('review_policy', 'Правила отзывов'), ('right_of_reply', 'Право на ответ'), ('privacy', 'Privacy'), ('terms', 'Terms')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'editorial policies',
                'ordering': ['kind', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MethodologyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('body', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
