from django.contrib import admin
from django.urls import path

from apps.ai_evidence.views import ai_evidence_capture
from apps.business.views import claim_profile, private_business_workspace, reputation_audit, submit_official_response
from apps.core.views import health, home
from apps.keywords.views import keyword_page_map_export_csv, keyword_report, markin_next_wave_export_csv, markin_relevance_blocks_csv
from apps.launchqa.launch_cut_views import (
    analytics_webmaster_readiness_csv,
    analytics_webmaster_readiness_json,
    analytics_webmaster_readiness_live_json,
    editorial_foundation_csv,
    editorial_foundation_json,
    editorial_foundation_live_json,
    final_launch_report_csv,
    final_launch_report_json,
    final_launch_report_live_json,
    first_index_batch_csv,
    launch_content_completeness_csv,
    launch_crawl_report_csv,
    launch_data_completeness_csv,
    launch_data_completeness_json,
    launch_data_completeness_live_json,
    operator_readiness_csv,
    origin_bot_qa_csv,
    p0_guide_content_csv,
    p0_guide_content_json,
    p0_guide_content_live_json,
    schema_crawl_eeat_csv,
    schema_crawl_eeat_json,
    schema_crawl_eeat_live_json,
    submission_evidence_csv,
    submission_evidence_json,
    submission_evidence_live_json,
)
from apps.launchqa.views import deployment_handoff_csv, deployment_handoff_dashboard, deployment_handoff_json, deployment_handoff_live_json, freshness_dashboard, submission_package_csv, submission_package_json, submission_package_live_json, indexing_monitor, launch_blocker_dashboard, launch_blocker_json, launch_ops_hub, launch_qa_checklist, release_readiness_json, route_smoke_export_csv, route_smoke_json, route_smoke_live_json, route_smoke_matrix, seo_audit_export_csv, webmaster_setup_checklist
from apps.pages.views import city_hub_page, city_service_page, company_dossier, for_business_page, guide_detail, guides_hub, kz_root_page, price_page, qr_landing, qr_platform_click, ranking_page, static_page
from apps.reviews.views import submit_review
from apps.search.views import autocomplete_view, search_view
from apps.seo.views import ai_reputation_md, llms_txt, robots_txt, sitemap_xml

urlpatterns = [
    path('admin/ai-evidence/capture/', ai_evidence_capture, name='ai_evidence_capture'),
    path('admin/keywords/report/', keyword_report, name='keyword_report'),
    path('admin/keywords/page-map-export.csv', keyword_page_map_export_csv, name='keyword_page_map_export_csv'),
    path('admin/keywords/markin-next-wave.csv', markin_next_wave_export_csv, name='markin_next_wave_export_csv'),
    path('admin/keywords/markin-relevance-blocks.csv', markin_relevance_blocks_csv, name='markin_relevance_blocks_csv'),
    path('admin/launch-qa/', launch_ops_hub, name='launch_ops_hub'),
    path('admin/launch-qa/blockers/', launch_blocker_dashboard, name='launch_blocker_dashboard'),
    path('admin/launch-qa/blockers.json', launch_blocker_json, name='launch_blocker_json'),
    path('admin/launch-qa/deployment-handoff/', deployment_handoff_dashboard, name='deployment_handoff_dashboard'),
    path('admin/launch-qa/deployment-handoff.json', deployment_handoff_json, name='deployment_handoff_json'),
    path('admin/launch-qa/deployment-handoff.csv', deployment_handoff_csv, name='deployment_handoff_csv'),
    path('admin/launch-qa/deployment-handoff-live.json', deployment_handoff_live_json, name='deployment_handoff_live_json'),
    path('admin/launch-qa/submission-package.json', submission_package_json, name='submission_package_json'),
    path('admin/launch-qa/submission-package.csv', submission_package_csv, name='submission_package_csv'),
    path('admin/launch-qa/submission-package-live.json', submission_package_live_json, name='submission_package_live_json'),
    path('admin/launch-qa/submission-evidence.json', submission_evidence_json, name='submission_evidence_json'),
    path('admin/launch-qa/submission-evidence.csv', submission_evidence_csv, name='submission_evidence_csv'),
    path('admin/launch-qa/submission-evidence.live.json', submission_evidence_live_json, name='submission_evidence_live_json'),
    path('admin/launch-qa/editorial-foundation.json', editorial_foundation_json, name='editorial_foundation_json'),
    path('admin/launch-qa/editorial-foundation.csv', editorial_foundation_csv, name='editorial_foundation_csv'),
    path('admin/launch-qa/editorial-foundation.live.json', editorial_foundation_live_json, name='editorial_foundation_live_json'),
    path('admin/launch-qa/launch-data-completeness.json', launch_data_completeness_json, name='launch_data_completeness_json'),
    path('admin/launch-qa/launch-data-completeness.csv', launch_data_completeness_csv, name='launch_data_completeness_csv'),
    path('admin/launch-qa/launch-data-completeness.live.json', launch_data_completeness_live_json, name='launch_data_completeness_live_json'),
    path('admin/launch-qa/p0-guide-content.json', p0_guide_content_json, name='p0_guide_content_json'),
    path('admin/launch-qa/p0-guide-content.csv', p0_guide_content_csv, name='p0_guide_content_csv'),
    path('admin/launch-qa/p0-guide-content.live.json', p0_guide_content_live_json, name='p0_guide_content_live_json'),
    path('admin/launch-qa/schema-crawl-eeat.json', schema_crawl_eeat_json, name='schema_crawl_eeat_json'),
    path('admin/launch-qa/schema-crawl-eeat.csv', schema_crawl_eeat_csv, name='schema_crawl_eeat_csv'),
    path('admin/launch-qa/schema-crawl-eeat.live.json', schema_crawl_eeat_live_json, name='schema_crawl_eeat_live_json'),
    path('admin/launch-qa/analytics-webmaster-readiness.json', analytics_webmaster_readiness_json, name='analytics_webmaster_readiness_json'),
    path('admin/launch-qa/analytics-webmaster-readiness.csv', analytics_webmaster_readiness_csv, name='analytics_webmaster_readiness_csv'),
    path('admin/launch-qa/analytics-webmaster-readiness.live.json', analytics_webmaster_readiness_live_json, name='analytics_webmaster_readiness_live_json'),
    path('admin/launch-qa/final-launch-report.json', final_launch_report_json, name='final_launch_report_json'),
    path('admin/launch-qa/final-launch-report.csv', final_launch_report_csv, name='final_launch_report_csv'),
    path('admin/launch-qa/final-launch-report.live.json', final_launch_report_live_json, name='final_launch_report_live_json'),
    path('admin/launch-qa/launch-content-completeness.csv', launch_content_completeness_csv, name='launch_content_completeness_csv'),
    path('admin/launch-qa/launch-crawl-report.csv', launch_crawl_report_csv, name='launch_crawl_report_csv'),
    path('admin/launch-qa/operator-readiness.csv', operator_readiness_csv, name='operator_readiness_csv'),
    path('admin/launch-qa/origin-bot-qa.csv', origin_bot_qa_csv, name='origin_bot_qa_csv'),
    path('admin/launch-qa/first-index-batch.csv', first_index_batch_csv, name='first_index_batch_csv'),
    path('admin/launch-qa/release-readiness.json', release_readiness_json, name='release_readiness_json'),
    path('admin/launch-qa/route-smoke/', route_smoke_matrix, name='route_smoke_matrix'),
    path('admin/launch-qa/route-smoke-export.csv', route_smoke_export_csv, name='route_smoke_export_csv'),
    path('admin/launch-qa/route-smoke.json', route_smoke_json, name='route_smoke_json'),
    path('admin/launch-qa/route-smoke-live.json', route_smoke_live_json, name='route_smoke_live_json'),
    path('admin/launch-qa/checklist/', launch_qa_checklist, name='launch_qa_checklist'),
    path('admin/launch-qa/freshness/', freshness_dashboard, name='freshness_dashboard'),
    path('admin/launch-qa/indexing-monitor/', indexing_monitor, name='indexing_monitor'),
    path('admin/launch-qa/seo-audit-export.csv', seo_audit_export_csv, name='seo_audit_export_csv'),
    path('admin/launch-qa/webmaster-checklist/', webmaster_setup_checklist, name='webmaster_setup_checklist'),
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('health/', health, name='health'),
    path('search/', search_view, name='search'),
    path('search/autocomplete/', autocomplete_view, name='search_autocomplete'),
    path('robots.txt', robots_txt, name='robots_txt'),
    path('sitemap.xml', sitemap_xml, name='sitemap_xml'),
    path('llms.txt', llms_txt, name='llms_txt'),
    path('ai-reputation.md', ai_reputation_md, name='ai_reputation_md'),
    path('kz/', kz_root_page, name='kz_root'),
    path('kz/<slug:city>/reyting-remontnyh-kompaniy/', ranking_page, name='ranking'),
    path('kz/<slug:city>/remont-kvartir/ceny/', price_page, name='price'),
    path('kz/company/<slug:slug>/reviews/new/', submit_review, name='submit_review'),
    path('kz/company/<slug:slug>/official-response/new/', submit_official_response, name='submit_official_response'),
    path('kz/company/<slug:slug>/', company_dossier, name='company_dossier'),
    path('kz/guides/', guides_hub, name='guides'),
    path('kz/guides/<slug:slug>/', guide_detail, name='guide_detail'),
    path('kz/<slug:city>/', city_hub_page, name='city_hub'),
    path('kz/<slug:city>/<slug:service_slug>/', city_service_page, name='city_service'),
    path('methodology/', static_page, {'page_key': 'methodology'}, name='methodology'),
    path('review-policy/', static_page, {'page_key': 'review_policy'}, name='review_policy'),
    path('right-of-reply/', static_page, {'page_key': 'right_of_reply'}, name='right_of_reply'),
    path('privacy/', static_page, {'page_key': 'privacy'}, name='privacy'),
    path('terms/', static_page, {'page_key': 'terms'}, name='terms'),
    path('for-business/', for_business_page, name='for_business'),
    path('claim-profile/', claim_profile, name='claim_profile'),
    path('reputation-audit/', reputation_audit, name='reputation_audit'),
    path('business/', private_business_workspace, name='private_business_workspace_root'),
    path('business/<path:path>/', private_business_workspace, name='private_business_workspace'),
    path('r/<slug:token>/<slug:platform>/', qr_platform_click, name='qr_platform_click'),
    path('r/<slug:token>/', qr_landing, name='qr_landing'),
]

